### ISSUE TITLE
feature render problem in chrome

### ISSUE THREAD

**Issue by atur** [openlayers/ol3#6083] opened 2016-11-07 10:36 UTC
ol3 and chrome 54.0.2840.87 m (64-bit) on win 10
When drawing many polygons and points in a map (> 1000), chrome some times dosent render the polygons right. 
Here is the map as it should be:
![chrome_ol_2](https://cloud.githubusercontent.com/assets/608436/20054534/9191cf48-a4dd-11e6-815e-b02c50170adf.jpg)
![chrome_ol_3](https://cloud.githubusercontent.com/assets/608436/20054562/b0587d82-a4dd-11e6-885c-dff7373cbb1a.jpg)

And here is how some times chrome render the map (exactly the same features as above). This dosent happens in firefox or ie:

![chrome_ol](https://cloud.githubusercontent.com/assets/608436/20054593/e70471e2-a4dd-11e6-85c7-8207e8e77899.jpg)
![chrome_ol_4](https://cloud.githubusercontent.com/assets/608436/20054599/ed19c82a-a4dd-11e6-835b-3d31e6c5d25d.jpg)

**Comment by ahocevar** [comment] 2016-11-07 11:26
Can you share your code in a JSFiddle so we can investigate?

**Comment by rcbull** [comment] 2016-11-15 04:52
Hi, I have same problem. Chrome version:  54.0.2840.99 m (64-bit
Problem does not occur in Edge or Firefox or Google Chrome Canary

See my test in JSFiddler https://jsfiddle.net/dgsxry0b/2/

**Comment by ahocevar** [comment] 2016-11-15 17:07
Cannot reproduce with Chrome 54.0.2840.98. Anyone can?

**Comment by rcbull** [comment] 2016-11-16 01:38
Hi,
try another test and see printscreen. If it does not, try refreshing the page a few times.

![image](https://cloud.githubusercontent.com/assets/451853/20331392/299ac31c-ab8c-11e6-9fa4-08e03ce79cd1.png)

**Comment by ahocevar** [comment] 2016-11-16 06:49
Sorry, I still cannot reproduce. I tend to say that this must be a Chrome renderer issue, not an OpenLayers issue.

**Comment by marcjansen** [comment] 2016-11-16 07:01
> https://rcbdesenvolvimento.com.br/sig/map.html

I also fail to reproduce this rendering, sorry (Chrome 51.0.2704.84 (64-bit), Linux)

**Comment by rcbull** [comment] 2016-11-16 09:46
I think it's the Chrome renderer too, but I try canvas x webgl and same results. Any suggestion?

**Comment by ahocevar** [comment] 2016-11-16 10:05
The webgl renderer currently does not render polygons and lines.

**Comment by probins** [comment] 2016-11-16 11:28
is this Windows-specific? Chrome stable is currently on slightly different versions for the different OSs https://omahaproxy.appspot.com/ Do you see the same problem in Chrome on say Android? I am not seeing this problem on Linux either.

**Comment by ahocevar** [comment] 2016-11-16 12:51
I tried on Windows and MacOS, and cannot reproduce on either.

**Comment by rcbull** [comment] 2016-12-28 18:38
The problem solved in Chrome version **55.0.2883.87 m (64-bit)**

**Comment by ahocevar** [comment] 2016-12-28 20:31
Thanks for your note @rcbull. So we can close this.

**Closed by ahocevar** 2016-12-28 20:31 UTC
