### ISSUE TITLE
ol3 is not usable with webpack.

### ISSUE THREAD

**Issue by aindlq** [openlayers/ol3#3162] opened 2015-01-22 12:15 UTC
It seems that openlayers should work when required from npm (I'm making this assumption because some key tickets related to npm were resolved and released - #3039, #3071).

But it doesn't work... I'm installing `openlayers` package from npm and then require it with `require('openlayers')`, but as a result I'm getting `Uncaught TypeError: Cannot read property 'protocol' of undefined` exception. It seems that for some reason goog.global.location is undefined.

Any ideas?

**Comment by tschaub** [comment] 2015-01-22 14:22
@artemkozlov - sorry you are having trouble.  I'll try to take some time to clarify things later today.

**Comment by elemoine** [comment] 2015-01-23 07:05
FWIW the problem seems related to the `ol.IS_HTTPS` variable.

**Comment by bartvde** [comment] 2015-01-23 13:00
I am seeing the same issue (but I am a nodejs noob anyway), curious to hear @tschaub's clarification

**Comment by tschaub** [comment] 2015-01-23 15:50
Please continue with your debugging.  The confusion I was referring to was about `dependencies` and `devDependencies` - not relevant to this issue (my hasty comment was in response to the title alone).

**Comment by bartvde** [comment] 2015-01-23 16:46
Yeah so the first issue is with ol.IS_HTTPS but there are more e.g.:

```
{return!1}}(),Yf="DeviceOrientationEvent"in ba,Zf="geolocation"in ba.navigator
                                                                    ^
TypeError: Cannot use 'in' operator to search for 'geolocation' in undefined
```

**Comment by bartvde** [comment] 2015-01-23 16:56
doing a simple test with google closure in node reveals the same:

```
/Users/bartvandeneijnden/opengeo/git/foo/goog/test.js:2
console.log(goog.global.location.protocol);
                                ^
TypeError: Cannot read property 'protocol' of undefined
    at Object.<anonymous> (/Users/bartvandeneijnden/opengeo/git/foo/goog/test.js:2:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
```

**Comment by bartvde** [comment] 2015-01-23 16:58
I'm guessing we should protect our code and default to certain values since ```goog.global.location``` is undefined in a nodejs environment

**Comment by elemoine** [comment] 2015-01-23 17:07
Guys, do you expect `require('openlayers')` to work in node? At this point, ol.js expects the global object (`goog.global`) to be `window`.

**Comment by artemkozlov** [comment] 2015-01-26 08:08
@elemoine I'm expecting it to work in browser with browserify/webpack.

**Comment by ThomasG77** [comment] 2015-01-26 22:46
I had some issues testing with Webpack but it works without any issue in Browserify.

Try:

    var ol = require('openlayers');
    // Your usual code

FYI, a bare minimum demo in [this GIST](https://gist.github.com/ThomasG77/7a92c94c6d7955fe81c9) using Browserify

**Comment by bartvde** [comment] 2015-01-27 07:50
thanks for supplying this @ThomasG77 would be great to have something for the docs later on

**Comment by Gijsjan** [comment] 2015-01-30 16:06
Having the same issue with webpack, but building is not a problem. Once I try to run it in the browser: `Uncaught TypeError: Cannot read property 'protocol' of undefined`. Same issue as @bartvde.

**Comment by bryanwood** [comment] 2015-03-20 08:22
Using this in webpack.config.js:
`loaders:[  {
              test:require.resolve('openlayers'),
              loader:"imports?define=>false"
            }]`
with `imports-loader` plugin got it working for me.

**Comment by aisaacs** [comment] 2015-04-03 19:24
If you are including a custom build of ol3 chances are the above may not work depending on how you include it - another solution is to test the name of the library using a regex:
{test: /ol-base\.js/, loader: 'imports?define=>false'},

**Comment by tschaub** [comment] 2015-04-04 13:59
Here is a demonstration of how the `openlayers` package can be used: https://gist.github.com/tschaub/1bdc2862a614c1dfeeb2#file-readme-md

This uses the full build and Browserify as a module loader & bundler.  We'll create a more complete tutorial for this.  And a separate tutorial should be created for Webpack.

We'll also shift things around so you don't need to install as much just to load the full build.  The other dependencies are about building a smaller profile of the library, and the original intention of the package on npm was to provide a set of build tools for the library, *not* a set of builds of the library.

It will be easier to create custom builds with the hosted build tool.  We'll also publish tutorials on how to create a custom build locally.

I'm closing this issue because I think the title is misleading at best.  If there are other valid issues that we should discuss, please open more tickets (e.g. if the way we wrap the build doesn't work with Webpack or something).

**Comment by tschaub** [comment] 2015-06-25 04:04
Reopening this issue with a new title.  I'm getting the same error as @aindlq when I try to use ol3 builds with Webpack, so I've clarified that this is a Webpack related issue.  @aindlq if you were not using Webpack when you encountered this issue, please reply.

**Closed** 2015-06-25 17:55 UTC

**Comment by magnusheino** [comment] 2015-10-09 20:52
How is this issue resolved? The problem is still there... or have I missed something?

Cannot use 'in' operator to search for 'geolocation' in undefined

**Comment by tschaub** [comment] 2015-10-10 03:11
@magnusheino likely a regression.  It was working with the changes in #3848.  If you can open a new issue that describes how to reproduce the problem, it will be easier to address.

**Comment by gwagener** [comment] 2015-11-25 19:44
Upgrading from 3.5 to 3.7, the minimal to get #3848, I still receive `Cannot use 'in' operator to search for 'geolocation' in undefined`, but upgrading to 3.11.2 fixed the issue.

**Comment by claycephas** [comment] 2016-01-06 04:54
Do you guys have any documentation of how to use this with webpack?

**Comment by tcoopman** [comment] 2016-01-06 06:55
@claycephas check out the `noParse` option from webpack. You basically say that old.js doesn't have to be parsed

**Comment by claycephas** [comment] 2016-01-06 21:37
Unfortunately, it looks like `noParse` causes `ol` to no longer be exported.

webpack config:

    config.module.noParse.push(/openlayers/);

my.js

    var ol = require('openlayers');
    console.log(ol); // undefined!

**Comment by tcoopman** [comment] 2016-01-09 08:20
@claycephas hmm, probably right. I just tried with the latest ol version and I don't seem to get the warning anymore. Can you try that?

**Comment by dharanid** [comment] 2016-01-12 12:29
@tcoopman 
I've updated my Open layers to 3.12.1 version.
Still i'm getting the warning.

any Ideas?

**Comment by tcoopman** [comment] 2016-01-16 08:07
@dharanid 
Yeah, something seems to have been wrong with my config, but with the noParse option I do get it working.

This is my working config:

```
   module: {
      loaders: [
        {test: /.*\.json$/, loader: 'json'},
        {test: /\.jsx?$/, exclude: /node_modules/, loaders: ['react-hot', 'babel'] },
        {test: /.*\.(gif|png|jpg)$/, loaders: ['file?hash=sha512&digest=hex&size=16&name=static/[hash].[ext]']}//, 'image?optimizationLevel=7&interlaced=false']}
      ],
      noParse: /dist\/ol.js/,
    },
```

**Comment by niba** [comment] 2016-01-18 13:52
@tcoopman 
I get this error when I'm trying to run mocha tests for my project. One of my files has reference to openlayers. Any ideas how to fix it?

Error:
```
ol.js:155
function Qi(b,c){var d=b.style;d.WebkitTransform=c;d.MozTransform
=c;d.a=c;d.msTransform=c;d.transform=c;Yb&&ic("9.0")&&(b.style.tr
ansformOrigin="0 0")}function Ri(b,c){var d;if(Pi()){var e=Array(
16);for(d=0;16>d;++d)e[d]=c[d].toFixed(6);Qi(b,"matrix3d("+e.join
(",")+")")}else if(Oi()){var e=[c[0],c[1],c[4],c[5],c[12],c[13]],
f=Array(6);for(d=0;6>d;++d)f[d]=e[d].toFixed(6);Qi(b,"matrix("+f.
join(",")+")")}else b.style.left=Math.round(c[12])+"px",b.style.t
op=Math.round(c[13])+"px"};var Si=["experimental-webgl","webgl","
webkit-3d","moz-webgl"];function Ti(b,c){var d,e,f=Si.length;for(
e=0;e<f;++e)try{if(d=b.getContext(Si[e],c))return d}catch(g){}ret
urn null};var Ui,Vi=ba.devicePixelRatio||1,Wi=!1,Xi=function(){if
(!("HTMLCanvasElement"in ba))return!1;try{var b=Ni();return b?(vo
id 0!==b.setLineDash&&(Wi=!0),!0):!1}catch(c){return!1}}(),Yi="De
viceOrientationEvent"in ba,Zi="geolocation"in ba.navigator,$i="on
touchstart"in ba,aj="PointerEvent"in ba,bj=!!                    
                                                                 
TypeError: Cannot use 'in' operator to search for 'geolocation' i
n undefined                                                      
```

**Comment by tcoopman** [comment] 2016-01-18 16:44
@niba openlayers has a dependency on the browser. Are you running your
tests in node or in the browser?

**Comment by niba** [comment] 2016-01-19 08:10
@tcoopman didn't know about that dependency. I was trying to run my tests in node with jsdom. Probably I need add karma to my project. Thanks!

**Comment by anthonyvialleton** [comment] 2016-11-08 09:22
Unable to make it work considering all the fixes in a React/Webpack (no server side rendering) context... Got always : 

`index.js?9778:47 Uncaught TypeError: Cannot read property 'bind' of undefined`

+

`ReactDOMComponentTree.js:107 Uncaught TypeError: Cannot read property '__reactInternalInstance$qkerh05c906p5f1wewswnrk9' of null`
