### ISSUE TITLE
Move dependendies to devDependencies

### ISSUE THREAD

**Issue by Delagen** [openlayers/ol3#4141] opened 2015-09-19 10:02 UTC
simple npm install download huge package with large dependencies such as browserify, but user may need only dist folder due use own build system

**Comment by claycephas** [comment] 2016-01-12 17:32
+1

**Comment by probins** [comment] 2016-10-13 10:19
duplicate of #3157?

**Comment by fredj** [comment] 2016-10-13 11:39
yes, it's a duplicate. Thanks @probins

**Closed by fredj** 2016-10-13 11:39 UTC
