### ISSUE TITLE
Support for TileUTFGrid layers using Mapbox API v4

### ISSUE THREAD

**Issue by aberenyi** [openlayers/ol3#5211] opened 2016-04-11 09:26 UTC
Gents - any particular reason why OL currently does not support Mapbox's latest (v4) API for `TileUTFGrid` layers?

Getting `Uncaught SyntaxError: Unexpected token :`, which suggests that this is some sort of a parser error?

Fiddle [here](http://jsfiddle.net/1t4anss3/).

Cheers

**Comment by fredj** [comment] 2016-04-11 11:22
The problem is that the v4 API doesn't support JSONP anymore

**Comment by fredj** [comment] 2016-04-11 12:05
We need to add a `jsonp` option to `ol.source.TileUTFGrid` (same as the one in `ol.source.TileJSON`)

**Comment by aberenyi** [comment] 2016-04-11 13:34
I think it is already [there](https://github.com/openlayers/ol3/blob/master/src/ol/source/tileutfgridsource.js#L53), isn't it?

**Comment by fredj** [comment] 2016-04-11 13:38
The `jsonp` option tells if the json file should be loaded via jsonp or xhr.
See https://github.com/openlayers/ol3/blob/v3.15.1/src/ol/source/tilejsonsource.js#L49

**Comment by aberenyi** [comment] 2016-04-11 13:43
Oh, I see, thanks. If I can carve out some time this week, I'll try to send a PR.

**Comment by fredj** [comment] 2016-05-17 06:28
fixed with #5329

**Closed by fredj** 2016-05-17 06:28 UTC
Labels: pull request accepted
