### ISSUE TITLE
SVG as layer not working(Chrome 51, FF 47)

### ISSUE THREAD

**Issue by davidxing616** [openlayers/ol3#5621] opened 2016-07-20 18:45 UTC
I have written a jsfiddle example using svg as a ImageStatic layer.

http://jsfiddle.net/gewq7rxt/

the example works properly in chrome 50 or below, and doesn't work in chrome 51. Other image type like png works for all versions of chrome.

**Comment by ahocevar** [comment] 2016-07-20 19:56
Duplicate of #5467.

**Closed by ahocevar** 2016-07-20 19:56 UTC
