### ISSUE TITLE
Freehand

### ISSUE THREAD

**Issue by stevben** [openlayers/ol3#2354] opened 2014-07-12 19:57 UTC
It will be very nice to have the Freehand feature as it exists in OL2.

See http://dev.openlayers.org/releases/OpenLayers-2.12/doc/devdocs/files/OpenLayers/Handler/Path-js.html

**Comment by tsauerwein** [comment] 2015-02-02 08:30
Closing as a duplicate of #2826

**Closed by tsauerwein** 2015-02-02 08:30 UTC
