### ISSUE TITLE
Reprojection on TileArcGISRest Tiles ignores PixelRatio on Tablets and phones and loads at 1:pixelratio size in map

### ISSUE THREAD

**Issue by flipper44** [openlayers/ol3#4583] opened 2015-12-21 17:11 UTC
TileArcGISRest ignores PixelRatio on Tablets and phones and loads at 1:pixelratio size in map.
It seems that I have no issues with other tile Sources rendering correctly. 
When viewing on a Device with a pixel Ratio of 2 The tile comes in at 1/2 Height and 1/2 width (1/4 the area it should cover). It seems to be bringing in all the necessary data (image area) but just isn't being sized UP. This leaves a pattern of tiles spaced out on a map.

**Comment by bartvde** [comment] 2015-12-21 17:13
what version of ol3? It should have been fixed with: https://github.com/openlayers/ol3/commit/8f1726ae3964b1713e7f90ac140af4f57f77593f#diff-f2c167c4469ad3177ad392a142422510

**Comment by flipper44** [comment] 2015-12-21 17:37
3.12.1
I believe I found the Underlying reason. I was Doing tile Reprojection from LL84 TileArcGISRest source to Spherical Mercator MAP..If I stick to LL84 on everything TileArcGISRest tiles display fine with other non TileArcGISRest tiles. When Reprojecting all Tiles are fine except the TileArcGISRest tiles which then exhibit the above described Issue.. Somewhat new to Tickets on GITHUB Should I edit the Ticket?

**Comment by bartvde** [comment] 2015-12-21 17:39
@petrsloup any ideas how this could relate to tile reprojection?

**Comment by bartvde** [comment] 2015-12-23 10:54
If I change the ```arcgis-tiled.html``` example to:

```
var layers = [
  new ol.layer.Tile({
    source: new ol.source.MapQuest({layer: 'sat'})
  }),
  new ol.layer.Tile({
    source: new ol.source.TileArcGISRest({
      url: url,
      projection: 'EPSG:4326'
    })
  })
];
var map = new ol.Map({
  layers: layers,
  target: 'map',
  view: new ol.View({
    center: [-10997148, 4569099],
    zoom: 4
  })
});
```

and use browser zoom (150%) I get this:

![screen shot 2015-12-23 at 11 53 22](https://cloud.githubusercontent.com/assets/319678/11975240/e9495f62-a96b-11e5-9e18-a2a064c889f1.png)

**Comment by bartvde** [comment] 2015-12-23 11:54
@flipper44 can you show a screenshot of your issue and/or a jsFiddle to reproduce?

**Comment by flipper44** [comment] 2015-12-23 13:45
@bartvde  I saw your screen shot in an email but don't see it on this site? I have a similar issue, but more pronounced on galaxy nexus 6 because of 3.5 pixel ratio..will attempt an attach when I get into the office

**Comment by bartvde** [comment] 2015-12-23 13:45
yeah I wasn't sure if my screenshot was representative, since I got the same with TileWMS and browser zoom.

**Comment by flipper44** [comment] 2015-12-23 15:37
![badtilearcgis](https://cloud.githubusercontent.com/assets/16003063/11979393/93c30024-a958-11e5-8f30-d1190b77a8a6.JPG)
This is what I get on a Nexus 6 (3.5 pixel ratio, Note: approx 3.5 times too small), also Tested on a Galaxy Note Pro 12.2" and similar effect just not as spaced out since pixel ratio isn't as high

**Comment by flipper44** [comment] 2015-12-23 15:39
Shoot TileWMS doesn't reproject either? that was my next layer to add

**Comment by bartvde** [comment] 2015-12-23 15:42
test it out and report back. What sources did work for you?

**Comment by flipper44** [comment] 2015-12-23 18:00
OK, I managed to get OSM, BING and Mapquest to all reproject so far...TileArcGISRest seems to be the only one I tried that is not working

**Comment by petrsloup** [comment] 2015-12-26 11:40
The tile reprojection is based on `tilePixelRatio` option of the `ol.source.Tile`.
This is not used by `ol.source.TileArcGISRest` and `ol.source.TileWMS`, so this is probably where the problem originates.
I'll look into it.

**Comment by petrsloup** [comment] 2015-12-28 12:32
This should be fixed in the current master with https://github.com/openlayers/ol3/pull/4598.

**Closed** 2015-12-28 12:31 UTC

**Comment by bartvde** [comment] 2015-12-28 13:48
thanks @petrsloup

**Comment by flipper44** [comment] 2015-12-28 15:50
Thanks,
I apologize in advance for this Question (Pretty new to GITHUB), but how do I implement this into my 3.12.1 Downloaded build, or how do I build a new ol.js and ol-debug.js from this in github? Couldn't find build docs.

**Comment by bartvde** [comment] 2015-12-28 16:24
see: https://github.com/openlayers/ol3/blob/master/DEVELOPING.md

**Comment by flipper44** [comment] 2015-12-28 17:17
Unfortunately I am on windows and a relative noob to Building Packages and repositories.
I saw that there was a build on https://travis-ci.org/openlayers/ol3/builds/99096485 and assumed that the newest builds could be reached through that site, but I am guessing those are local builds and not available online. 

I've had to use my Scaleline and proj4js projection(units) Workaround from #4572 so I am stuck in ol-debug anyways for now. I may just have to put the newest changes into my currently modified file to get by for now. Hate to use ol-debug but I will probably have to for now, and then wait for a new incremental release.
Thank You for all the help.

**Comment by flipper44** [comment] 2015-12-28 17:38
Looks like their are way more than a few changes to several files since the 3.12.1 release so this is unlikely very doable for myself manually. I will see if I can figure it out on windows, this is going to be a learning experience. I wish the Builds run in Travis were available online.

**Comment by flipper44** [comment] 2015-12-30 18:33
Took half a day but I got cygwin to work and Make a build that included my scaleline changes from Workaround from #4572. 
How do I get the interest of the right person re: the scaleline not working Across Units? and the Issue with proj4js Units I mentioned in the Issue, so that I don't have to create custom builds. I would ask for a pull but I know that some of the logic is likely unnecessary in my code and wouldn't want to break something that the logic might have been in place for?
