### ISSUE TITLE
leaked objects

### ISSUE THREAD

**Issue by ghettovoice** [openlayers/ol3#3292] opened 2015-02-28 18:35 UTC
Hi, for all!
I need to show and close map in some window widget and expect that after removing all layers, deleting all references to ol3 objects memory will be freed by GC. But I noticed on memory snapshot that they are still in memory.

Can somebody explain is this expected behavior? If so, how can I totally clear all references for CG and free memory after map destruction? I need it because layers in my app have huge number of objects, not killed objects consume all memory after several create/destroy operations.

I wrote simple test example, after N add/remove buttons click you will see on memory snapshot that here N ol.Map and N * 1000 ol.Feature leaked instances. they are retained by event listeners
```
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>ol test</title>

    <style>
        html, body { height : 100%; }

        #buttons {
            position : absolute;
            left     : 0;
            top      : 0;
        }
    </style>

    <script src="ol-debug.js"></script>
</head>
<body>
<div id="map" style="height: 100%"></div>
<div id="buttons">
    <button id="add">add</button>
    <button id="remove">Remove</button>
</div>

<script>
    var map, vector, raster;

    document.getElementById("add").addEventListener("click", function(e) {
        e.preventDefault();

        addMap();
    });

    document.getElementById("remove").addEventListener("click", function(e) {
        e.preventDefault();

        removeMap();
    });

    function addMap() {
        vector = new ol.layer.Vector({
            source: new ol.source.Vector()
        });

        var count = 1000;
        var e = 4500000;

        for (var i = 0; i < count; ++i) {
            var coordinates = [2 * e * Math.random() - e, 2 * e * Math.random() - e];
            var feature = new ol.Feature({
                id: i,
                geometry: new ol.geom.Point(coordinates)
            });

            feature.setId(i);

            vector.getSource().addFeature(feature);
        }

        raster = new ol.layer.Tile({
            source: new ol.source.MapQuest({ layer: 'sat' })
        });

        map = new ol.Map({
            layers: [raster, vector],
            target: 'map',
            view: new ol.View({
                center: [0, 0],
                zoom: 2
            })
        });
    }

    function removeMap() {
        vector.getSource().clear();
        map.removeLayer(vector);
        map.removeLayer(raster);
        vector = null;
        raster = null;  

        map.setTarget(null);
        map = null;
    }
</script>
</body>
</html>
```
my snapshots
![scr1](https://cloud.githubusercontent.com/assets/4323000/6427412/9e8f9f88-bf90-11e4-8fbf-9c92a33e15a1.png)
![src2](https://cloud.githubusercontent.com/assets/4323000/6427413/9e90532e-bf90-11e4-94de-4deab2492ecb.png)

**Comment by ahocevar** [comment] 2015-03-01 16:40
Here is a JSFiddle with the above code: http://jsfiddle.net/p74qterc/2/. I can reproduce the issue, but right now I am clueless about why this issue exists.

**Comment by elemoine** [comment] 2015-03-01 16:44
I haven't looked at your examples, but what if you force the GC to run by using the development tools?

**Comment by ahocevar** [comment] 2015-03-01 17:17
> I haven't looked at your examples, but what if you force the GC to run by using the development tools?

I did that already - to no avail. There seems to be a memory leak indeed.

**Comment by tschaub** [comment] 2015-03-01 17:46
Some potentially relevant things:

 * the map's shared tile queue may be creating problems - a tile queue per tile source could be a more direct way to manage things
 * tile listeners aren't unregistered until tiles are purged from the queue, tiles aren't purged from the queue until it is full
 * the map should no longer need to register the single `handleTileChange_` listener - image tile sources listen for tile changes and fire tile load related events, here they could also dispatch a change event, layers would trigger the same, and the map would re-render

I haven't tried to reproduce this, but I'm curious who retains a reference to `tileChangeCallback_` (or the tile queue) in the second snapshot above.  If nobody retains a reference to the map, I would think this would be available to garbage collection.

**Comment by ghettovoice** [comment] 2015-03-01 18:03
> I haven't looked at your examples, but what if you force the GC to run by using the development tools?

Confirm the above, after forcing GC didn't resolve issue

**Comment by tschaub** [comment] 2015-03-01 18:23
So I imagine this could be due to tile event listeners not being unregistered until tiles are purged from the tile queue.  If there is a retained reference to the listener (e.g. a global one from `goog`) it would make sense that things could not be garbage collected (until tiles were purged from the tile queue).  Again, I'm interested to see who retains a reference to `tileChangeCallback_` above.

**Comment by elemoine** [comment] 2015-03-02 08:06
> tile listeners aren't unregistered until tiles are purged from the queue, tiles aren't purged from the queue until it is full

The tile queue [registers](https://github.com/openlayers/ol3/blob/master/src/ol/tilequeue.js#L95-L96) tile listeners, but I do not see where the tile listeners are unregistered. Could you please point me to the code where the unregistration occurs?

> Again, I'm interested to see who retains a reference to tileChangeCallback_ above.

What worries me the most right now is the `change` listeners on the tiles.

**Comment by fredj** [comment] 2015-03-02 16:05
The controls and interactions (at least) are keeping a reference to the map

**Comment by fredj** [comment] 2015-03-02 16:44
I've started to work on this: https://github.com/openlayers/ol3/compare/master...fredj:dispose

**Comment by fredj** [comment] 2015-03-03 14:24
> The tile queue registers tile listeners, but I do not see where the tile listeners are unregistered. Could you please point me to the code where the unregistration occurs?

When the queue is full, the tiles are [removed and disposed](https://github.com/openlayers/ol3/blob/master/src/ol/tilecache.js#L50), the `load` and `error` listeners are correctly [removed](https://github.com/openlayers/ol3/blob/master/src/ol/imagetile.js#L71) but not the `change` listener in `ol.TileQueue#loadMoreTiles`.

**Comment by elemoine** [comment] 2015-03-03 14:45
> When the queue is full, the tiles are removed and disposed,

It's not the tile queue, it's the tile cache in the source. This is different.

**Comment by fredj** [comment] 2015-03-26 08:24
What about exporting the `ol.Map#dispose` function?

**Comment by bartvde** [comment] 2015-04-04 11:57
@elemoine can this be closed now that @3420 is merged?

**Comment by elemoine** [comment] 2015-04-04 11:59
Yes.

**Closed by elemoine** 2015-04-04 11:59 UTC

**Comment by chenyo2691** [comment] 2018-06-12 03:11
why merge ?and its not solved
