### ISSUE TITLE
Uncaught assertion error with Bing maps source

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#3247] opened 2015-02-16 22:20 UTC
With the [`ol.source.BingMaps` examples](http://openlayers.org/en/master/examples/bing-maps.html?mode=raw), if you zoom all the way out you get an assertion error.

**Comment by fredj** [comment] 2015-02-25 08:53
duplicate of #2780

**Closed by fredj** 2015-02-25 08:53 UTC
