### ISSUE TITLE
Problem with zooming and resolution of the map

### ISSUE THREAD

**Issue by matiasbarone** [openlayers/ol3#2849] opened 2014-10-17 11:01 UTC
When I zoom out, reload the page and then zoom in, the resolution of the map is wrong.
It seem that the api make some calculation when it reload but not fix it when zooming.

I don't sure if this is a bug, is a problem with the code (how the map is initialized) or is how the api should work, I make the test in the example that compare webgl, canvas and dom.

Here is how the map is afeter zooming in.
![chrome 37 0 1](https://cloud.githubusercontent.com/assets/5585590/4677711/9828e2b2-55eb-11e4-81b6-9e171930b014.png)

I make the test in Chrome 37, Firefox 32 on Ubuntu and Debian.

Thank you

**Comment by fredj** [comment] 2016-04-14 13:28
duplicate of #2904

**Closed by fredj** 2016-04-14 13:28 UTC
