### ISSUE TITLE
JSFiddle examples broken

### ISSUE THREAD

**Issue by tschaub** [openlayers/ol3#5250] opened 2016-04-19 14:34 UTC
If you go to [one of the hosted examples](http://openlayers.org/en/v3.15.1/examples/simple.html) and click "edit" you get taken to JSFiddle but the example doesn't work.

In the console are two errors related to http://jsfiddle.net/css//css/light.css?update_19_04_2016_1 not being found.  And one uncaught `ReferenceError: ol is not defined`.

**Comment by probins** [comment] 2016-04-19 14:39
if you click 'run', though, it still works

**Comment by jonataswalker** [comment] 2016-10-14 13:03
At least for me this is caused by Mixed Content - HTTP (OL files) resources load over HTTPS.

**Comment by fredj** [comment] 2016-10-17 12:45
fixed with  #5976

**Closed by fredj** 2016-10-17 12:45 UTC

**Comment by tschaub** [comment] 2016-10-17 20:06
It looks examples still don't run on load.  For example, open https://openlayers.org/en/v3.15.1/examples/simple.html and click the "Edit" button.

Curious if this is the way it has to be.

**Comment by jonataswalker** [comment] 2016-10-17 20:22
> if you click 'run', though, it still works

Now this is valid.
