### ISSUE TITLE
View/Tile loading does not respect extent defined (XYZ source).

### ISSUE THREAD

**Issue by felixveysseyre** [openlayers/ol3#5489] opened 2016-06-16 14:55 UTC
Hi,

I have developed a large image viewer on top of OpenLayers3.16.

To do that, I am using a XYZ source and a custom extent.

In this example, my image size is (width, height) = (33864,22561) px. Therefore there is 9 level of zoom available.

![6](https://cloud.githubusercontent.com/assets/4909259/16121287/f9d9001a-33e2-11e6-961d-422fedf4e4fa.png)

Here is the projection I am using:
```
new ol.proj.Projection({
	code: 'pixels',
	units: 'pixels',
	extent: [0, 0, currentData.view.width, currentData.view.height]
});
```

Here is the view I am using:
```
new ol.View({
	center: [currentData.view.width / 2, currentData.view.height / 2],
	zoom: currentData.view.zoom.default
	maxZoom: currentData.view.zoom.max,
	projection: projection
});
```

Despite setting this view, OpenLayers seems to use a larger view and try to unload unexisting tiles (see image):
![5](https://cloud.githubusercontent.com/assets/4909259/16121046/f747e3bc-33e1-11e6-9203-fc7bfeb04e7b.png)

Here is the tiles OpenLayers tried to load:

- (x, y) = (0, 0): correct
- (x, y) = (1, 0): correct
- (x, y) = (0, 1): not-correct
- (x, y) = (1, 1): not-correct

I do not know what type info should I add to this issue to help solving.
Is this a bug, or do I use something incorrectly ?

Thanks for your help.

**Comment by ahocevar** [comment] 2016-06-17 07:19
Can you put your code in a JSFiddle? This is very likely a configuration issue, but it's hard to analyze without seeing it live.

**Comment by felixveysseyre** [comment] 2016-06-17 08:32
@ahocevar 

Here is a simplified version of my code: http://jsfiddle.net/3d7mrths/1/

Thanks for you help !

**Comment by ahocevar** [comment] 2016-06-20 12:02
It is *both* a configuration issue and a bug. You'll need to configure your layer with an extent too:
```js
var layer = new ol.layer.Tile({
  source: source,
  maxZoom: zoomMax,
  extent: [0, 0, width, height]
});
```
For the bug, we have a fix already which will be merged soon: #5482.

**Closed** 2016-06-30 21:19 UTC

**Comment by felixveysseyre** [comment] 2016-07-04 09:26
I have updated my code with the latest OpenLayers version (3.17.1) and the layer fix you suggested.

Unfortunately, despite the extent seems to be different, OpenLayers is still trying to load tiles which do not exist. I have tried with a square image and everything is working correctly.

For the dimension of the image used in my JSFiddle, the Z value (of the XYZ source) used to load the image seems to be incorrect.
I managed to correct the tile loaded using the following transformation: `Zcorrected = Z + 1;`

Could a bug still exist ?

**Comment by ahocevar** [comment] 2016-07-04 10:45
If you look at your tile at zoom level 0, you will see that it only uses half of the size. So you need to adjust the layer extent to do the same. See http://jsfiddle.net/otbvz824/ for an updated fiddle that does this.

**Comment by felixveysseyre** [comment] 2016-07-26 15:45
@ahocevar Since I add the extent to my layer, I have some problems while rotating my view.
Weird thing, it seems to depend on my window size.

<img width="1034" alt="capture d ecran 2016-07-26 a 17 42 29" src="https://cloud.githubusercontent.com/assets/4909259/17144876/93334664-5358-11e6-9bdd-591f997f9787.png">
<img width="992" alt="capture d ecran 2016-07-26 a 17 42 39" src="https://cloud.githubusercontent.com/assets/4909259/17144874/932b6638-5358-11e6-9474-2df4703a2c9b.png">
<img width="1000" alt="capture d ecran 2016-07-26 a 17 42 50" src="https://cloud.githubusercontent.com/assets/4909259/17144875/932fe190-5358-11e6-90e2-059ccfacaa7f.png">

Removing the extent from the view solves the problem.

Should I add something else to make it work correctly ?

Here is my rotation function:

```
var rotation = view.getRotation();

if(type == 'left')
{
	rotation -= Math.PI / 8;
}
else if(type == 'right')
{
	rotation += Math.PI / 8;
}

view.setRotation(rotation);
```

**Comment by ahocevar** [comment] 2016-07-28 14:10
If I rotate the map in the fiddle I linked above (drag with alt-ctrl or alt-cmd), I cannot reproduce this.

**Comment by felixveysseyre** [comment] 2016-08-12 11:06
Thank for your return @ahocevar !

I found something very weird. Depending on the screen I use to display the fiddle, the result of the rotation is not the same.

I have created the issue #5716.

**Comment by felixveysseyre** [comment] 2016-08-12 14:23
@ahocevar Based on http://jsfiddle.net/otbvz824/, I tried to build a function computing the correct extent and view center for a given image.

The values returned by my function seem correct but the view display by OpenLayers seems incorrect: http://jsfiddle.net/otbvz824/2/

I am doing something incorrectly ?

**Comment by ahocevar** [comment] 2016-08-12 17:30
This is a bug in OpenLayers which you cannot really work around at the application level, except for configuring `pixelRatio: 1` on the map.

**Comment by ahocevar** [comment] 2016-08-12 17:31
See #5716 for the bug.
