### ISSUE TITLE
Can not serializing Style objects or include them in Feature object.

### ISSUE THREAD

**Issue by AndreasRohl** [openlayers/ol3#4759] opened 2016-01-31 20:44 UTC
When creating a Feature with a geometry you can serialize this with a GeoGSON object but too my surprise the style is not honored. Too me the Feature object does not provide that much additional benefit compared a simple Geometry object. Perhaps the style can be included since it does have a setStyle method. Another way would be to provide a way to serialize the Style object separately and you could included in the GeoGSON using a props object. 

Example:
This simple style 

 var newStyle = new ol.style.Style({
                stroke: new ol.style.Stroke({
                  color: 'yellow',
                  width: 1
                }),
                fill: new ol.style.Fill({
                  color: 'rgba(255, 255, 0, 0.1)'
              })
            });

Will look like this if you print it:
{\"i\":null,\"g\":{\"a\":\"rgba(255, 255, 0, 0.1)\"},\"f\":null,\"b\":{\"a\":\"yellow\",\"b\":null,\"f\":1},\"j\":null}

**Comment by bartvde** [comment] 2016-02-01 09:41
Duplicate of #3069

**Closed by bartvde** 2016-02-01 09:41 UTC

**Comment by ca0v** [comment] 2016-07-23 03:26
Doesn't have to be GeoJSON+CSS but just a way to serialize and deserialize a style would allow for sharing style across projects.

**Comment by ahocevar** [comment] 2016-07-23 07:16
A good format for serializing and deserializing styles is the Mapbox-gl-style format (see https://github.com/mapbox/mapbox-gl-style-spec/). I am currently working on a small stand-alone library that converts these styles into OpenLayers style functions. I am hoping to be able to finish it in the next 1-2 months.

**Comment by probins** [comment] 2016-07-23 07:34
related to #2697

**Comment by ca0v** [comment] 2016-07-25 23:43
@ahocevar I like it.  It is a complete map configuration so we could de/serialize the entire map?  But I'm not seeing how to apply a style to an individual feature.  My two cents:

1. Please consider typescript when developing your standalone library:

`
	declare module MapBoxStyleSpec {
	
	    export interface Vector {
	        type: string;
	        url: string;
	    }
	
	    export interface Raster {
	        type: string;
	        url: string;
	    }
	
	    export interface Sources {
	        vector: Vector;
	        raster: Raster;
	    }
	
	    export interface Layout {
	    }
	
	    export interface Paint {
	    }
	
	    export interface Layer {
	        id: string;
	        source: string;
	        source-layer: string;
	        type: string;
	        ref: string;
	        filter: string[];
	        layout: Layout;
	        paint: Paint;
	    }
	
	    export interface Map {
	        version: number;
	        sources: Sources;
	        layers: Layer[];
	    }
	
	}
`
2. I guess it has been decided against but even with the advanced (and complex) mapbox 'styling' I think something closer to the ol3 metal would be very good for us if it were presented as one of many ways to serialize/deserialize styles (like ol.format):

`
	declare namespace MyPreferredStyleFormatter {
	
	    export interface Fill {
	        color?: string;
	    }
	
	    export interface Stroke {
	        color?: string;
	        width?: number;
	    }
	
	    export interface Circle {
	        fill?: Fill;
	        opacity?: number;
	        stroke?: Stroke;
	        radius?: number;
	    }
	
	    export interface Text {
	        fill?: Fill;
	        stroke?: Stroke;
	        text?: string;
	        "offset-x"?: number;
	        "offset-y"?: number;
	        font?: string;
	    }
	
	    export interface Style {
	        star?: any; // any style with 'points'
	        circle?: Circle;
	        text?: Text;
	    }
	
	}
`

**Comment by ahocevar** [comment] 2016-07-28 14:13
@ca0v Yes, you could serialize/deserialize a complete map configuration with mapbox-gl-style. But the library I'm working on will only make use of the style definition for a single layer.

**Comment by pilatte** [comment] 2022-06-08 23:01
Hey, I know it's been a while since this issue came up but I made a [thing](https://github.com/pilatte/ol-json-styles):

```js
import { loadStyle } from "ol-json-style";

const json = {
    Style: {
        fill: {
            Fill: {
                color: "red",
            },
        },
        stroke: {
            Stroke: {
                color: "blue",
            },
        },
    },
};

const myStyle = loadStyle(json);

// You can then use it in a layer
const layer = new VectorLayer({
    source: mySource,
    style: myStyle,
});
```

It's my very first npm package so please be nice 😉
