### ISSUE TITLE
ol.control.OverviewMap - pan via overviewmap

### ISSUE THREAD

**Issue by Apophis3000** [openlayers/ol3#3795] opened 2015-06-12 07:14 UTC
In Openlayers2 it was possible (as far as I know) to move the map via the overviewmap itself. This would allow the user to switch quickly between far away locations without having to zoomout and back into the new position again.

I there is no way to do this yet, an option for this in the overviewmap would be great.

**Comment by bartvde** [comment] 2015-06-12 07:20
duplicate of #3753

**Closed by bartvde** 2015-06-12 07:20 UTC
