### ISSUE TITLE
"main" property in package.json

### ISSUE THREAD

**Issue by hckhanh** [openlayers/ol3#6214] opened 2016-12-07 04:19 UTC
For best practice, you should not use the minified version of ol.js in `main` property of **package.json** file.
When someone uses `import` or `require`. It will read from that file. It's not good for debugging.

You should configure the `main` property like this:

```json
{
  "main": "dist/ol-debug.js"
}
```

**Comment by tschaub** [comment] 2016-12-09 17:18
Thanks for the suggestion @hckhanh.  The current [`openlayers` package](https://www.npmjs.com/package/openlayers) isn't well suited for direct use with `import` or `require`.  The package was intended to be used as a way to generate a custom build of the library.  Unfortunately, this isn't easy for anyone to do unless they are intimate with the Closure Compiler or the build tools we provide for it.

There are two problems with the current `dist/ol.js` which make it unsuitable to be `import`ed or `require`d directly.  1) It is huge - including far more than anybody needs to use in a single application (e.g. two renderers, many source types and formats, etc.), and 2) it is impossible to debug.

Your proposal would address the second problem (impossible to debug) but would exacerbate the first (huge).

I'm going to close this issue because I don't think we want to encourage people to use the full build.  This sucks because we don't have an easy-to-use alternative - although we do provide some documentation on [creating custom builds](https://openlayers.org/en/latest/doc/tutorials/custom-builds.html).

One nice alternative would be for our hosted full build to be a useful debug build.  That is, it should point to a sourcemap that pulls in the sources [we already host](http://openlayers.org/en/v3.19.1/ol/ol/map.js) for each release.  This would make getting started with OpenLayers a bit easier - people would include a script tag pointing to the hosted build and would get a nice debugging experience.

For `import` and `require` support, I don't think we should work toward a single `main` for the library.  Instead, I think people should import just what they need.  E.g.
```js
var XYZ = require('ol/source/XYZ');
// or
import XYZ from 'ol/source/XYZ';
```

We are making progress toward this goal.  The first big part of the effort was getting rid of our dependency on the Closure Library.  The next was reorganizing our files and "exports."  We should soon be able to publish an [`ol` package](https://www.npmjs.com/package/ol) that lets you do what I've described above (this is not yet ready).

**Closed by tschaub** 2016-12-09 17:18 UTC
