### ISSUE TITLE
Bower repository

### ISSUE THREAD

**Issue by hastebrot** [openlayers/ol3#3119] opened 2015-01-13 03:14 UTC
Hi!

I've searched for a Bower repository that provides a pre-build ol3 distribution and found https://github.com/nd0ut/ol3-bower and https://github.com/Yann29/bower-ol3 so far. Unfortunately both are outdated and one provides to much files (API docs, examples, ...). I decided to add the official release zip file to my `bower.json`. But this will use a lot of space (more than 100 MB) in `bower_components`.

~~~json
{
  "name": "ol3-demo",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "ol3": "https://github.com/openlayers/ol3/releases/download/v3.1.1/v3.1.1.zip"
  }
}
~~~

So I'm up to provide ol3 releases for Bower myself. From the best practices I so far saw in the wild I think this repository should be named `ol3-dist` and contain a `bower.json`, the `LICENSE.md` from `openlayers/ol3` and a `README.md` describing how to use it in Bower. It should also contain the directory `dist` with the JavaScript and CSS files taken from the official release zip. Maybe I'll rename these files to `ol.js`, `ol.min.js`, `ol.css` and `ol.min.css` to more resemble "best practices". New releases to Bower should be automated, so I will also work a bit on that.

My question is, if someone is interested in officially providing a Bower distribution under the `openlayers` GitHub organization.

**Comment by ahocevar** [comment] 2015-01-13 08:14
Thanks for willing to help out! We are aware of the problem of the release artifacts taking up too much space (see #3078), and we are definitely willing to provide an official Bower distribution under the `openlayers` organization. @tschaub and @elemoine are currently working on making the `dist` folder work for this purpose (see e.g. #3115), which is also required for npm distributions (see #3071).

**Comment by dabos-GFI** [comment] 2015-01-19 13:01
Hello,

For your information, you can use the github syntax for bower, i.e:
```json
{
    "name": "awesome",
    "version": "1.0.0",
    "dependencies": {
        "ol3": "openlayers/ol3#3.1.1"
    }
}
```

But it requires that you build ol3 after downloading, a dist github repository with tag and release will be perfect.

**Comment by hastebrot** [comment] 2015-01-19 13:14
I've put an experimental Bower distribution to https://github.com/hastebrot/ol3-dist. 

The idea is to put the distributions into a separate Git repository. I don't know much about the `bower install` process, but suspect Bower fetches the whole source code via GitHub archive functionality and removes the files that are marked as ignored in `bower.json`. This would mean it downloads the whole distribution, unpacks it and removes the files, which causes a lot of network traffic, thus the slimed down distribution in a separate repository.

**Comment by dabos-GFI** [comment] 2015-01-19 13:21
Nice and very usefull, thanks :)

**Comment by Toub** [comment] 2015-02-23 17:36
+1 for official npm/bower ol3 distributions

**Comment by ahocevar** [comment] 2015-02-23 17:37
npm is available already: https://www.npmjs.com/package/openlayers.

**Comment by carueda** [comment] 2015-04-08 19:42
:+1: for official bower ol3 distribution

**Comment by szabyg** [comment] 2015-04-23 08:57
+1 for official bower ol3 distribution
IMO npm is good for nodejs tools/projects, bower is better for frontend dependencies.
See http://blog.stackfull.com/2013/05/publishing-bower-components/ for tutorial.

**Comment by tschaub** [comment] 2015-04-23 15:59
Everybody knows that you need `npm` and `package.json` for Bower, right?  If you just add [`openlayers`](https://www.npmjs.com/package/openlayers) to your `package.json`, you'll get it on `npm install` (which you need to get Bower as well).  You can remove one step in fetching your dependencies by ditching Bower (trust me, I've been there).

**Comment by elemoine** [comment] 2015-04-23 16:08
https://twitter.com/iamdevloper/status/586094415975952384

**Comment by szabyg** [comment] 2015-04-23 18:22
> Everybody knows that you need npm and package.json for Bower, right? If you just add openlayers to your package.json, you'll get it on npm install (which you need to get Bower as well). You can remove one step in fetching your dependencies by ditching Bower (trust me, I've been there).

For small projects without a build process that's true. But if you have 100+ source files you need build tools like grunt or gulp and 10+ dependencies to do everything neat and automatized. You'll use npm packages (with nodejs). Then you have 10+ UI component dependencies, all of which are available as bower packages, except ol3. You're suggesting me to write an extra gulp task that copies ol3 from my node_modules folder (where my build tools are) to my bower components folder where it actually belongs to. Sure, it's possible but for me it's adding a step, not removing one. It's also possible to cut a tree with a fish. It's just not made for it. ;-) 

npm: "node package manager"
bower: "A package manager for the web" /see bower.io/

**Comment by juristr** [comment] 2015-04-23 20:13
agree! It seems there is a tendency away from bower towards npm (or even jspm), but currently bower is the most used for UI  frontend packages. Lots of tools and predefined build processes rely on that. In fact, I had to create my own private bower package for ol3 separately as there isn't an official one. That kinda sucks. I also don't get why people start discussing on this matter, why not just set it up, it's a couple of minutes.
Whether it is good or bad to have so many different package managers is a totally different and at the same time valid discussion. But that shouldn't take place here.

**Comment by dabos-GFI** [comment] 2015-04-24 09:33
Hi!
What I've done for using bower was to create a shim repository for the dist.
then use the following command line (bower github syntax) to add the dependency in my project.
```sh
    $ bower install dabos-GFI/ol3#3.3.0 --save
```

You can find similar shim for other well-known component here : https://github.com/components/components
It will be best to use a master openlayers/ol3-dist instead or components/ol3.

Hope it will help :)

**Comment by juristr** [comment] 2015-04-24 09:36
ya sure, that's what you normally do. But I'd like to avoid that (as in that case I have to handle upgrades etc..) or depend on [unofficial bower packages](https://github.com/nd0ut/ol3-bower), especially given how easy it is to create and publish a bower package.

**Comment by kiRach** [comment] 2015-04-29 09:34
:+1: Can't believe this awesome library still hasn't bower support

**Comment by Diaaz** [comment] 2015-05-04 12:32
Could you please make a bower repository with the current release version? It would save every developer so much time. Thanks!

**Comment by hastebrot** [comment] 2015-05-04 13:35
@Diaaz The current release version [1] has the file `v3.4.0-dist.zip` (807 KB) under downloads. You can use it as I wrote in my OP.

[1] https://github.com/openlayers/ol3/releases/tag/v3.4.0

**Comment by hastebrot** [comment] 2015-05-04 13:47
I've updated my unofficial ol3-dist Bower repository (https://github.com/hastebrot/ol3-dist) from Version 3.1.1 to 3.4.0. This repository contains the distribution and source files and is updated unregulary.

**Comment by Diaaz** [comment] 2015-05-04 13:51
@hastebrot Thanks! I think there should be an official release because now the distribution locations change and because of that the references in our sourcecode needs to be changed as well. First the distribution used was openlayers3, then ol3, now o3-dist.

**Comment by sjuanman** [comment] 2015-06-12 10:24
+1 for an official bower pre-build release

**Comment by suguiura** [comment] 2015-06-22 18:28
Seems like we have a bunch of bower repositories for openlayers for today:

    $ bower search ol3
    Search results:

        openlayers3 git://github.com/dummas/ol3.git
        ol3 git://github.com/Yann29/bower-ol3.git
        ol3-unofficial git://github.com/nd0ut/ol3-bower.git
        ol3-scripts git://github.com/luscus/ol3-scripts.git
        ol3-gamma4 git://github.com/Yann29/bower-ol3-gamma4.git
        bbol3 git://github.com/atlefren/BBol3.git
        openlayers3.5 git://github.com/openlayers/ol3.git
        ol3-layerswitcher git://github.com/walkermatt/ol3-layerswitcher.git
        ol3-popup git://github.com/walkermatt/ol3-popup.git
        openlayers3.4.0 git://github.com/openlayers/ol3.git
        OpenLayersIII git://github.com/openlayers/ol3.git
        OpenLayers git://github.com/openlayers/ol3.git

It would be interesting to normalize the official distribution to either "ol3" or "openlayers3", instead of leaving it to some unofficial ones. It would be also interesting to select the package version using the bower notation: `bower install ol3#3.6.0`

**Comment by Pedrazl** [comment] 2015-08-10 08:12
+1 to @szabyg comment. It has no sense the need to create a special grunt task just for openlayers library. The actual situation with bower and openlayers is caothic, please fix it.

**Comment by thiswildorchid** [comment] 2015-08-10 23:12
+1

**Comment by ezze** [comment] 2015-08-19 14:10
+1 for official Bower package!

**Comment by jessemarple** [comment] 2015-08-31 20:57
+1 for official package

**Comment by zhulinpinyu** [comment] 2015-09-06 04:05
+1 for official package

**Comment by shvelo** [comment] 2015-09-08 14:05
Do it already, what's the big issue

**Comment by nmeln** [comment] 2015-10-10 22:12
Please fix this

**Comment by joshuamarquez** [comment] 2015-10-14 18:08
+1 for official package

**Comment by craigsnyders** [comment] 2015-10-14 20:55
+1 for official bower support

**Comment by zussel** [comment] 2015-10-15 11:15
+1 for official bower support

**Comment by mhdev90** [comment] 2015-10-26 13:16
+1 for official bower support

**Comment by chrispyleLAC** [comment] 2015-11-09 09:01
+1 for official bower support

**Comment by ktraff** [comment] 2015-11-10 23:50
+1 for official bower support

**Comment by andokai** [comment] 2015-11-11 09:12
+1

**Comment by thomasoberthanner** [comment] 2015-11-13 20:53
+10 ;-) for official bower support

**Comment by bartvde** [comment] 2015-11-13 21:54
https://twitter.com/nachocoloma/status/663622545162280960

**Comment by marcjansen** [comment] 2015-11-13 21:56
Didn't know that, @bartvde

**Comment by tschaub** [comment] 2015-11-14 05:30
See also https://github.com/bower/bower/pull/1748#issuecomment-150104311.  It won't be long now.

**Comment by tschaub** [comment] 2015-11-14 06:36
This is a thoughtful writeup: http://gofore.com/ohjelmistokehitys/stop-using-bower/

Regarding the @hastebrot's original question:

> My question is, if someone is interested in officially providing a Bower distribution under the openlayers GitHub organization.

I think it is clear there is not interest in providing a Bower distribution.  We have been publishing an archive that includes a debug build, the full build, and CSS for each release - without the extra weight of the API docs, examples, etc.  See https://github.com/openlayers/ol3/releases/download/v3.11.1/v3.11.1-dist.zip for example.  I assume that people could use this URL in their `bower.json`.  And you can get the same by adding `openlayers` to your `package.json`.

Still, the full build of OpenLayers is *not* something you should be using in production.  Instead, people should be [creating custom builds](http://openlayers.org/en/v3.11.1/doc/tutorials/custom-builds.html).  It is abundantly clear that this is more work than people are willing to accept.  We're working on ways to make the library more consumable with tools like Browserify and webpack - but this is not yet complete (and a ton of work remains).  At least when you add the package as a dependency to your `package.json`, you get the tools you need to create a custom build.  The same is not possible with Bower.

Publishing the full build of OpenLayers to the Bower repository would be providing another wrong way to use the library.  So I'm going to close this issue to remove any expectations about this happening.  Feel free to leave your comments, but we would also appreciate help in making it easier to create custom builds.  Meaning, we'd appreciate it more if you would make contributions to the documentation or build tools.

**Closed by tschaub** 2015-11-14 06:36 UTC

**Comment by dabos-GFI** [comment] 2015-11-15 10:23
Hello,

At first, I really does not understand the choice made to not provide a dedicated distribution repository for ol3, like https://github.com/components/components (they are not specifically dedicated to bower).
It should not be the developers to decide the way the library is used, and they should help the community to make easier to integrate the code with all available toolchain.
With a such decision you continue to enforce some developers to have their fork instead of contributing to the main repository.

**Comment by tschaub** [comment] 2015-11-15 22:19
@dabos-GFI (and anybody else using Bower), does this work for you?

`bower.json` ~

```json
  "dependencies": {
    "openlayers": "https://github.com/openlayers/ol3/releases/download/v3.11.1/v3.11.1-dist.zip"
  }
```
?

**Comment by tschaub** [comment] 2015-11-15 22:26
I just tried this:
```
mkdir test-bower
cd test-bower
npm init --yes
npm install bower --save-dev
./node_modules/.bin/bower install openlayers=https://github.com/openlayers/ol3/releases/download/v3.11.1/v3.11.1-dist.zip
```

And I get the following in `./bower_components/openlayers/`
```
ol-debug.js	ol.css		ol.js
```

**Comment by lazaruslarue** [comment] 2015-12-04 19:11
@tschaub that's working for me. thanks very much :)

**Comment by lazaruslarue** [comment] 2015-12-16 12:51
jfyi @tschaub and others, be aware this will fail when the powers of `Node 0.12` && `Bower 1.7.1` combine: https://github.com/bower/bower/issues/2101

**Comment by tschaub** [comment] 2015-12-16 18:36
Thanks for the head's up @lazaruslarue.  It looks like people should avoid upgrading to `bowser@1.7.1` if they use URLs to zip archives (perhaps not only from GitHub).  Since this is an acknowledged bug, I assume it will be fixed in an upcoming release.

**Comment by rixlabs** [comment] 2015-12-17 12:40
Still cannot understand why you don't want an official bower repo but it works

**Comment by sombriks** [comment] 2016-11-05 20:31
i can confirm that bower accepts and correctly install openlayers from https://github.com/openlayers/ol3/releases/download/v3.11.1/v3.11.1-dist.zip

using this command:

bower install https://github.com/openlayers/ol3/releases/download/v3.11.1/v3.11.1-dist.zip --save

the death of bower is long announced, yet it lasts.

personally i'll move to a browserified setup (maybe a webpack one, but i like to have the choice), but the solution pointed here will help those who simply need to maintain any already exsisting solution.

**Comment by hastebrot** [comment] 2016-11-05 23:12
>the death of bower is long announced, yet it lasts.

I don't know how this works, but maybe `yarn` can provide Bower-like functionality and host the artifacts in the npm registry.

**Comment by sombriks** [comment] 2016-11-05 23:21
@hastebrot IMO the issue is solved, i just used bower to install the zip file. I had to do that because the legacy project setup.

on new projects the npm, i think, is the better way.
