### ISSUE TITLE
ol.interaction.Select layers param

### ISSUE THREAD

**Issue by ArmandBahi** [openlayers/ol3#4782] opened 2016-02-03 14:32 UTC
Hello, 

When adding a selection like this:

```
this.selectHover_ = new ol.interaction.Select({
    layers: [this.openLayersOverlay_],
    condition: ol.events.condition.pointerMove,
});
```

the selectHover_ hightlights all the features from all the layers.

For using only the this.openLayersOverlay_ features I have to do this: 

```
this.selectHover_ = new ol.interaction.Select({
    layers: [this.openLayersOverlay_],
    condition: ol.events.condition.pointerMove,
    filter: function(feature, layer){
        if(layer === this_.openLayersOverlay_)
            return true;
        else
            return false;
    }
});
```

Is it normal ? the "layers" param is working ?

**Comment by ahocevar** [comment] 2016-02-03 14:37
Duplicate of #4631.

**Closed by ahocevar** 2016-02-03 14:37 UTC
