### ISSUE TITLE
Fill style feature by an image

### ISSUE THREAD

**Issue by MrPl0p** [openlayers/ol3#3310] opened 2015-03-04 08:01 UTC
Hello, 

I realized that openlayers 3 does not benefit from all the canvas renderer capabilities. And I would like tu upgrade it by for example let us fill style the feature with an image and not only a color.
This could simulate for example an hatch pattern that we had in OL2 or all of icon backgrounds we can imagine.

Do you think this will be used by the community ?

Thank you.

**Comment by ahocevar** [comment] 2015-03-04 11:47
Such a contribution would be much appreciated. Thanks in advance!

**Comment by tsauerwein** [comment] 2015-03-04 12:40
I'm closing this issue as a duplicate of #2208. But yes, support for patterns/background images would be welcome!

**Closed by tsauerwein** 2015-03-04 12:40 UTC
