### ISSUE TITLE
Tiled WMS Layer Visibility Issue

### ISSUE THREAD

**Issue by issue01001** [openlayers/ol3#5305] opened 2016-05-03 07:00 UTC
I am getting an issue when using tiled wms services, but the issue is only apparent with certain conditions in place;

- The 3.15.1 version of openlayers
- Latest version of Chrome browser
- Few computers with same OS and mostly the same software as others in the office

I am able to view the tiled WMS example on the site perfectly fine on a few other computers in the office. However when the small group of computers on the same network with the same OS and Chrome version try to view the tiled WMS layers, the tiles don't seem to be rendering, although I do see that the tiles are being received in the network tab of the console. They also seem to work perfectly fine with older versions of openlayers prior to v3.15 and work fine on Firefox. Here are the two examples from the site on one of the computers with this issue, both receive the tiles according to the console's network tab and only the older version of ol3 seems to render them properly:
![a1](https://cloud.githubusercontent.com/assets/19163451/14976601/c021dd3c-1115-11e6-9496-5b54cfa14831.png)
![a2](https://cloud.githubusercontent.com/assets/19163451/14976602/c0286878-1115-11e6-9466-e931e6e51a39.png)

Any feedback on this would be appreciated, if anyone else has come across a similar issue and have found out the cause for this, I would love to hear your solution. Thanks in advance.

**Comment by bartvde** [comment] 2016-05-03 07:50
can you try disabling hardware acceleration? See also: #5251 and #5236

**Comment by issue01001** [comment] 2016-05-03 08:57
I will try disabling hardware acceleration on chrome once I am back at the office, thank you for your fast response.

**Comment by retif** [comment] 2016-05-05 08:00
confirm on windows 7, chrome 50.0.2661.94 m, ol 3.14.2. disabling hardware acceleration helps.

**Comment by ahocevar** [comment] 2016-05-08 08:53
We need to collect as much information as we can about this issue, and create or find a Chrome bug report.

**Comment by ahocevar** [comment] 2016-05-08 09:01
I'm wondering if this is related to the problem described in http://stackoverflow.com/questions/27922062/canvas-rendering-issues-with-chrome-39-and-hardware-acceleration. Can users affected by the problem reported here please check if they are also affected by the problem reported there?

**Comment by JelmerBaas** [comment] 2016-05-08 12:06
The source image that fiddle uses doesn't exist anymore.

I just checked the original issue (http://openlayers.org/en/v3.15.1/examples/wms-tiled.html) on my desktop at home, that works fine.Windows 10 vs Windows 7, but both AMD cards. Oddly enough, I also see the issue via a remote desktop session, which should is a completely different system.

#5308, #5305 and #5236 should be merged somehow imho, maybe even together with #5251

**Comment by fioru89** [comment] 2016-05-08 18:36
Video bug
https://youtu.be/CI_4JnP1hUc

**Comment by JelmerBaas** [comment] 2016-05-09 06:31
Yep - exactly the issue I experience here.

**Comment by Nalcom** [comment] 2016-05-11 11:28
I tried the differents versions of OL because I'd this problem.

For your information it work with version 13.x and versions 14.0 and 14.1 but from version 14.2 the problem appeared.

Thank you OL-dev for your work.

**Comment by ahocevar** [comment] 2016-05-11 12:45
I was finally able to reproduce the issue, created a minimal example, and reported a Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=611022.

**Comment by fredj** [comment] 2016-05-11 12:58
Thanks @ahocevar !

**Comment by ahocevar** [comment] 2016-10-07 09:05
According to https://bugs.chromium.org/p/chromium/issues/detail?id=611022, recent Chrome versions do not have this bug any more.

**Closed by ahocevar** 2016-10-07 09:05 UTC
