### ISSUE TITLE
redirect to the latest version of the api doc

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3#4507] opened 2015-12-01 11:29 UTC
It would be nice if when browsing an old version of the api doc, a message is displayed to use the latest version.
Something like: "This version of the documentation is outdated! Click here for the latest released version"

**Comment by ahocevar** [comment] 2015-12-01 12:04
Not sure about this. The API docs have to match the version of the library to be useful, and the reader may not be using the latest version of the library. An alternative solution might be to mention the version in a prominent place on each API docs page.

**Comment by tonio** [comment] 2015-12-01 12:41
The problem is that Goggle refers to various version of the api when
searching with it.
You never know which version you browse, except with the URL.

Being able to clearly see current version & go to «latest stable» &
«master» should be doable without manually changing url.

On 1 December 2015 at 13:04, Andreas Hocevar <notifications@github.com>
wrote:

> Not sure about this. The API docs have to match the version of the library
> to be useful, and the reader may not be using the latest version of the
> library. An alternative solution might be to mention the version in a
> prominent place on each API docs page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openlayers/ol3/issues/4507#issuecomment-160947664>.
>



-- 
Antoine Abt

Camptocamp France SAS
http://www.camptocamp.com

**Comment by ahocevar** [comment] 2015-12-01 13:22
Yes, a link to the latest release API makes sense, and also clearly displaying the release the reader is currently viewing.

**Comment by ahocevar** [comment] 2016-05-11 12:15
Fixed with #5330.

**Comment by ahocevar** [comment] 2016-05-11 14:55
Fixed with openlayers/openlayers.github.io#70

**Closed by ahocevar** 2016-05-11 14:55 UTC
Labels: pull request accepted
