### ISSUE TITLE
Map not moving at MS Edge on Win10 Mobile

### ISSUE THREAD

**Issue by goshi** [openlayers/ol3#4262] opened 2015-10-13 13:02 UTC
When click to the map and try to move it - nothing happens. Zoom works fine. Clicks on the overlays work fine too. 
Tested on the map on main page openlayers.org and projects for some clients

**Comment by ahocevar** [comment] 2015-10-13 13:17
Have you tried the latest version, v3.10.1? This issue should be fixed already. Try e.g. with http://openlayers.org/en/v3.10.1/examples/simple.html.

**Comment by fredj** [comment] 2015-10-13 13:24
Caused by #4167 (v3.10.1 if affected too).
I'm on it.

**Comment by goshi** [comment] 2015-10-13 13:29
Nope, not works. Edge version 20.10536.1004.0

**Comment by fredj** [comment] 2015-10-13 13:57
@goshi the issue is now fixed in the master branch. Thanks for the report.
You can tests it here: http://openlayers.org/en/master/examples/

**Closed by fredj** 2015-10-13 13:57 UTC

**Comment by goshi** [comment] 2015-10-13 14:00
Thanks, @fredj. Now it is ok!
