### ISSUE TITLE
OL3 OverviewMap is not as powerful as OL2

### ISSUE THREAD

**Issue by christopheblin** [openlayers/ol3#3809] opened 2015-06-16 08:41 UTC
In OpenLayers2, the overviewmap is draggable, which is not the case in OL3.

See http://stackoverflow.com/questions/30806253/openlayers3-draggable-overviewmapcontrol for more details

Is that considered an issue or not ?

**Comment by bartvde** [comment] 2015-06-16 08:44
Please search before you open up a new issue.
Duplicate of #3753

**Closed by bartvde** 2015-06-16 08:44 UTC
