### ISSUE TITLE
TopoJson source does not render different fill styles if there is a stroke style

### ISSUE THREAD

**Issue by jnachtigall** [openlayers/ol3#6284] opened 2016-12-20 14:09 UTC
I have a vector layer based on a TopoJson source where each feature should get a different `fill` color and `stroke`. 

For example, each country could be filled with a different color:

![2016-12-20 14_54_58-edit fiddle - jsfiddle - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/21353012/5a1c221c-c6c4-11e6-84a4-1ef3f09407f3.png)

This is working with the following styleFunction:

```js
  style: function (feature, res) {
      var randomColor = getRandomColor();
      var colorStyle = new ol.style.Style({
        fill: new ol.style.Fill({
          color: randomColor
        }),
        // ADD THIS STROKE AND IT IS NOT WORKING ANYMORE
        // stroke: new ol.style.Stroke({
        //  color: '#ffffff',
        //  width: 1
        // })
        // END
      });
      
      // this comes from the original stuff, so just keeping it:
      // don't want to render the full world polygon, which repeats all countries
      return feature.getId() !== undefined ? colorStyle : null;
    }
```

However, if I add a `stroke` next to the `fill` of this style (just comment out in the above code), then always the very first style is used and the style is not updated anymore:
```js
        stroke: new ol.style.Stroke({
          color: '#ffffff',
          width: 1
        })
```

![2016-12-20 15_02_55-edit fiddle - jsfiddle - firefox developer edition](https://cloud.githubusercontent.com/assets/3307404/21353237/6db8057e-c6c5-11e6-8551-9364a9be33b4.png)

Interestingly, this it seems like this does not happen if the source is geojson based instead of topojson. 

Here's a [JsFiddle](https://jsfiddle.net/ewweccx1/3/) so can try yourself. Simply add/remove the `stroke` style to see the difference. Any ideas where this comes from or how to debug it further?

**Comment by jnachtigall** [comment] 2016-12-20 14:12
Maybe this is a dupe of #6199?

**Comment by ahocevar** [comment] 2016-12-20 14:16
Duplicate of #6199.

**Comment by ahocevar** [comment] 2016-12-20 14:16
As a workaround for now, remove the `duplicates: false` option on your `ol.source.Vector` instance.

**Closed by ahocevar** 2016-12-20 14:16 UTC

**Comment by jnachtigall** [comment] 2016-12-20 14:30
@ahocevar There's no `duplicates` option. I guess you mean `overlaps: false` should be removed (which works. Thank you!)

**Comment by ahocevar** [comment] 2016-12-20 19:26
Yes, I meant `overlaps: false`. Just edited my comment. Thanks @jnachtigall.
