### ISSUE TITLE
 Disable interim tiles for tile layer

### ISSUE THREAD

**Issue by JelmerBaas** [openlayers/ol3#5251] opened 2016-04-19 14:40 UTC
This is an exact cross post from a Stackoverflow question I asked a while back (http://stackoverflow.com/questions/36567347/disable-interim-tiles-for-tile-layer) , but thought I'd paste it here since it didn't get any response:

> When creating a map like this:
> 
> var map = new ol.Map({
>    loadTilesWhileAnimating: true,
>    loadTilesWhileInteracting: true
> })
> 
> OpenLayers 3 uses interim tiles (i.e., previously loaded lower resolution tiles) when zooming and panning until it has finished loading the new tiles. The interim tiles are placed behind the real tiles. Which is very clever, and is great for opaque layers, but much not so great for mostly transparent layers.
> 
> We currently have a layer which consists of just a few lines, only a few pixels think. Slightly panning the map makes these into huge blobs, causes a lot of flicker.
> 
> Is there a way to disable creating of these interim tiles, just for a specific layer? It would be disappointing if I'd need to disable both loadTilesWhile* properties just because of a single layer.
> 
> For an example, see: http://imgur.com/RbtmkpT The left is normal (the red line is mine), right is after panning slightly.
> 
> This is with cacheSize 0 on the source and useInterimTilesOnError false.
> 
> Update: OpenLayers 3.12 behaves differently. In that version, only unloaded tiles are blurry (which is to be expected), but already loaded tiles are left alone. Starting from 3.13 or 3.14, this behavior changed.
> 

Because of this issue, we can't upgrade to 3.14 or 3.15 without disabling loadTilesWhileAnimating (which creates more visual loading time for our users).

I see three solutions:

- Revert to the way OL 3.12 worked;
- Make loadTilesWhileAnimating a per-layer setting;
- Load tiles while animating, but don't use tiles from a much different zoom level.

**Comment by tschaub** [comment] 2016-04-19 16:01
I imagine in most cases, using interim tiles only makes sense on the "base" layer in a map.  And we'd probably see performance improvements if this was the default behavior.

Maybe it would make sense to have a map-level `useInterimTiles` option in addition to layer-level `useInterimTiles` options.  When resolving the layer states, we could check for these options and use the following logic:

 * if no `useInterimTiles` option on the map, then the first visible layer defaults to `true` and all others default to `false`
 * if `useInterimTiles` is `true` on the map, then it defaults to `true` for all layers
 * if `useInterimTiles` is `false` on the map, then it default to `false` for all layers
 * apply any `useInterimTiles` options per-layer

**Comment by JelmerBaas** [comment] 2016-04-20 08:02
This sounds excellent!

If I can assist with testing or something else, please let me know.

**Comment by ahocevar** [comment] 2016-04-20 08:11
@JelmerBaas Which OpenLayers version did you use for creating the http://imgur.com/RbtmkpT screenshots? I think this may be due to a temporary bug in v3.14.0, which should be fixed now. I would be interested to hear if you get the same behaviour with v3.15.1.

**Comment by JelmerBaas** [comment] 2016-04-20 08:25
The left part is 3.12, the right part is 3.15.1. 

I simply showed the full map, then zoomed in by drawing a tiny zoom rectangle. The right part is zoom level 17, and the intermediate shown is from zoom 10 or so.

**Comment by ahocevar** [comment] 2016-04-20 08:26
@JelmerBaas What was the source type used for the overlay in that screenshot? If I remember correctly, we added an `opaque: true` default to some sources, like `ol.source.OSM`. Try to explicitly set `opaque: false` on the overlay source.

**Comment by JelmerBaas** [comment] 2016-04-20 08:33
I'm using an OSM source. Just tried the opaque option and that actually changes the behavior to what OpenLayers 3.12 did, great!

I saw this option before, but never thought of trying it out somehow.

I think it would still be great to have the ability to disable intermediate tiles, but at least now they don't fill the whole screen anymore.

**Comment by JelmerBaas** [comment] 2016-04-20 14:01
Update: there's another issue I just found. It seems Google Chrome doesn't work properly with 3.15.1. Only a small part of the overlay (the 2nd tile layer which I just switched to opaque: false) is drawn. 

When panning, the part is shortly visible, but then hidden again.
(See: http://imgur.com/FdDZ3hJ)

**Comment by ahocevar** [comment] 2016-04-21 08:00
That sounds very strange. Can you put up a JSFiddle to reproduce this issue? And you're saying this only happens in Chrome?

**Comment by ahocevar** [comment] 2016-04-21 08:05
Also, I note that #4939 was already merged in v3.14.1.

**Comment by JelmerBaas** [comment] 2016-04-21 08:12
I just re-checked: this issue is not present in v3.14.1, but it is from v3.14.2 and onwards. I'll do my best to create a JSFiddle, but I'll have to figure something out with the non-opaque layer (my layer can't be used since that's sensitive customer data).

**Comment by JelmerBaas** [comment] 2016-04-21 08:43
I've made a simple test case which shows what I mean:
http://jsfiddle.net/rdpjfj03/2/

Oddly enough, when I replace my own layer with another (just tried OpenCycleMap, to have something), it does work properly: http://jsfiddle.net/rdpjfj03/4/

So it might be related to my PNG files?

**Comment by ahocevar** [comment] 2016-04-21 09:20
I tried with your fiddle, but could not get into a state that looks like on your screenshot. What are the steps to reproduce? And again, does this only happen in Chrome? Which OS, which version?

**Comment by JelmerBaas** [comment] 2016-04-21 09:29
I've just had my colleagues this the same fiddle (should've done that earlier), and it seems related to my machine. I'm using Windows 7 with the newest Google Chrome.
This is what I see: http://imgur.com/a/nzQkc
After disabling hardware acceleration in Chrome, it DOES work. I'll see if there's a newer version of my video card drivers...

**Comment by ahocevar** [comment] 2016-04-21 10:54
> After disabling hardware acceleration in Chrome, it DOES work.

Maybe related to https://github.com/openlayers/ol3/issues/5236#issuecomment-211965648.

**Comment by ahocevar** [comment] 2016-05-11 12:51
Duplicate of #5305. See https://github.com/openlayers/ol3/issues/5305#issuecomment-218448195

**Closed by ahocevar** 2016-05-11 12:51 UTC
