### ISSUE TITLE
(enhancement) Fill style feature by a canvas pattern

### ISSUE THREAD

**Issue by BevolutionZ** [openlayers/ol3#3451] opened 2015-04-01 10:49 UTC
As montioned in https://github.com/openlayers/ol3/issues/2208 , it would be nice to create canvas pattern to style features of a layer. the target is to perform a client thematic as what this textures.js is offering (http://riccardoscalco.github.io/textures/)

Best regards

**Comment by tsauerwein** [comment] 2015-04-02 05:51
Closing this as a duplicate of #2208

**Closed by tsauerwein** 2015-04-02 05:51 UTC
