### ISSUE TITLE
I stop working code and examples

### ISSUE THREAD

**Issue by fioru89** [openlayers/ol3#5308] opened 2016-05-03 14:48 UTC
Today, after updating the browser Google Chrome and Mozilla stopped working my OpenLayers codes and examples on your site.
Partially various layers not running, such as for example:
http://openlayers.org/en/v3.15.1/examples/layer-group.html
http://openlayers.org/en/v3.15.1/examples/layer-extent.html
http://openlayers.org/en/v3.15.1/examples/reprojection-image.html
and many others...

**Comment by fioru89** [comment] 2016-05-03 14:55
http://i77.fastpic.ru/big/2016/0503/d3/1fa459b03dce02cd9f725536fd9404d3.png

**Comment by fredj** [comment] 2016-05-03 15:20
Same issue as #5305 ?

**Comment by probins** [comment] 2016-05-03 15:22
I was just going to ask that. I don't see any issues on my Linux-based Chrome (other than a few missing MapBox tiles), so is this Windows-specific again?

**Comment by fioru89** [comment] 2016-05-08 18:36
Video bug
https://youtu.be/CI_4JnP1hUc

**Comment by ahocevar** [comment] 2016-05-11 12:50
Duplicate of #5305. See https://github.com/openlayers/ol3/issues/5305#issuecomment-218448195

**Closed by ahocevar** 2016-05-11 12:50 UTC
