### ISSUE TITLE
v3.14.0 breaking ol.source.XYZ?

### ISSUE THREAD

**Issue by jvanulde** [openlayers/ol3#4911] opened 2016-02-24 22:03 UTC
The following no longer works in v3.14.0:
   
    var projection = ol.proj.get('EPSG:3978');

    var mapView = {
        extent: [ -2750000.0, -900000.0, 3600000.0, 4630000.0 ],
        projection: projection
    };

    var resolutions = [
        38364.660062653464,
        22489.62831258996,
        13229.193125052918,
        7937.5158750317505,
        4630.2175937685215,
        2645.8386250105837,
        1587.5031750063501,
        926.0435187537042,
        529.1677250021168,
        317.50063500127004,
        185.20870375074085,
        111.12522225044451,
        66.1459656252646,
        38.36466006265346,
        22.48962831258996,
        13.229193125052918,
        7.9375158750317505,
        4.6302175937685215
	];

    var matrixIds = new Array( resolutions.length );

    for ( z = 0; z < resolutions.length; ++z ) {
        matrixIds[ z ] = z;
    }

    var layer = new ol.layer.Tile( {
        source: new ol.source.XYZ( {
            url: 'http://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/CBMT_CBCT_GEOM_3978/MapServer/tile/{z}/{y}/{x}',
            tileGrid : new ol.tilegrid.TileGrid( {
                extent: [ -2750000.0, -900000.0, 3600000.0, 4630000.0 ],
                origin : [ -3.46558E7, 3.931E7 ],
                resolutions : resolutions,
                matrixIds : matrixIds
            } )
        } )
    } )

**Comment by ahocevar** [comment] 2016-02-24 22:05
Can you be a bit more specific about what exactly no longer works? Or provide a JSFiddle with the above code in action?

**Comment by ahocevar** [comment] 2016-02-24 22:10
Here is a [JSFiddle](http://jsfiddle.net/9aefhx14/) I created from your snippet above, which works just fine.

**Comment by jvanulde** [comment] 2016-02-24 22:37
So I may have jumped to conclusions here. I had to make a small change to my code to get it to work. I was creating a view with an extent and projection then calling view.fit as follows:

    var map = new ol.Map({
        layers: [layer],
        target: 'map',
        view: new ol.View( {
            extent: [ -2750000.0, -900000.0, 3600000.0, 4630000.0 ],
            projection: projection
        })
    });

    map.getView().fit(  [ -2750000.0, -900000.0, 3600000.0, 4630000.0 ], map.getSize() );

If I amend your fiddle as above I get a map but it only loads one tile: [http://jsfiddle.net/jvanulde/qrr3gz3p/1/](http://jsfiddle.net/jvanulde/qrr3gz3p/1/)

This used to work fine until I upgraded to 3.14.0. If I remove the extent and projection from the view constructor everything works as expected.

**Comment by ahocevar** [comment] 2016-02-25 06:42
To me, the result looks expected. `ol.View#fit()` zooms the map to an extent that fits the whole specified extent. This is the same extent as the one of the tile grid, so you naturally get unmapped areas in the map viewport. The extent on the view only constrains map navigation to that extent, so you cannot pan the map to outside the viewport.

I created another version of the Fiddle which uses v3.13.1: http://jsfiddle.net/qrr3gz3p/2/. You can see that the result is exactly the same.

Am I missing something? If not, please close this issue.

**Comment by jvanulde** [comment] 2016-02-25 13:38
In your example I see the same issue in that only one tile gets loaded and changing the map view (pan, zoom, etc.) doesn't result in more tiles being loaded.

**Comment by ahocevar** [comment] 2016-02-25 14:44
I see now what the problem is. It is with your code: `ol.source.XYZ` uses the EPSG:3857 projection by default. You previously didn't run into problems with it because OpenLayers did not have raster reprojection. I updated your fiddle to use `ol.source.TileImage` instead: http://jsfiddle.net/qrr3gz3p/3/, which does not have a default projection.

**Comment by ahocevar** [comment] 2016-02-25 22:30
Can we close this @jvanulde?

**Closed** 2016-02-26 15:28 UTC
