### ISSUE TITLE
Wrong longitude

### ISSUE THREAD

**Issue by jeansouza** [openlayers/ol3#5203] opened 2016-04-08 12:08 UTC
When I move the map to the left or to the right, the longitude keeps growing, and that's not correct.

This can be seen here:

http://openlayers.org/en/v3.15.1/examples/mouse-position.html?q=position

**Comment by fredj** [comment] 2016-04-11 08:19
Duplicate of #3899

**Closed by fredj** 2016-04-11 08:19 UTC
