### ISSUE TITLE
Tiny gap between vector tiles

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [openlayers/ol3#3799] opened 2015-06-12 19:58 UTC
In my testcase http://drifted.in/other/ol/tiles.html there is a tiny gap between tiles even though the GeoJSON coordinates are same.

    7/68/84 - xMax: 1565430.3392804079 (meters)
    7/68/85 - xMin: 1565430.3392804079

As this gap is same also when zooming in (that gap doesn't grow), I suspect it is caused rather by the library (rounding ?) than by my data.

**Comment by jan-tosovsky-cz** [comment] 2015-11-14 19:00
Example updated to 3.11 (TileVector -> VectorTile)
http://drifted.in/other/ol/tiles_v3_11.html

**Comment by tsauerwein** [comment] 2015-11-21 11:35
Are you using a buffer for your tiles? Usually vector tiles do not only contain the data inside the tile boundary but also the data within a small buffer on each edge. The renderer for `ol.layer.TileVector` will then clip to the original tile boundaries.

**Comment by jan-tosovsky-cz** [comment] 2015-11-21 20:50
@tsauerwein there is no buffer. Vector data is clipped already. I have no control over this.

**Comment by jan-tosovsky-cz** [comment] 2015-11-21 20:56
I've found 3.11 version works fine in Chrome/Edge. The only problematic is FF.
That TileVector (old) example gives same incorrect result for all FF/Chrome/Edge browsers.

**Comment by ahocevar** [comment] 2015-12-04 13:32
Can this be closed as duplicate of #4501?

**Comment by jan-tosovsky-cz** [comment] 2015-12-04 20:14
I agree to mark it as a duplicate of #4329 although the original issue has been 'fixed' by removing TileVector class from the library ;-)

**Closed** 2015-12-04 21:22 UTC
