### ISSUE TITLE
Layer disappears at high-ish zoom-levels (in Firefox)

### ISSUE THREAD

**Issue by thomasmoelhave** [openlayers/ol3#3337] opened 2015-03-09 20:38 UTC
Tiles suddenly disappear at moderately high zoom-levels,  at least in Firefox using the canvas renderer. This can be confirmed from the [OpenLayers WMTS example](http://openlayers.org/en/v3.3.0/examples/wmts.html), both in production (v3.3.0) and development mode. Have a look at this screenshot:

![firefox_vs_chromium](https://cloud.githubusercontent.com/assets/179143/6563334/bdb740fe-c676-11e4-957a-3ac8e2106871.png)

On the left we have a recent Chromium, and the right a recent Firefox both showing the OpenLayers WMTS example zoomed in on the port of Seattle at the same zoom-level.  Notice that the WMTS tiles are *not* shown in Firefox, but they do show up in Chromium.

Some observations:
  * If I zoom out Firefox will start showing the WMTS layer again. If I zoom further in, the tiles still do not appear.
  * This is not specific to WMTS layers, it also happens in the [WMS example](http://openlayers.org/en/v3.3.0/examples/wms-image.html)

  * It does *not* happen in the [XYZ example](http://openlayers.org/en/v3.3.0/examples/xyz.html). 

  * I cannot reproduce this issue with the DOM renderer.

  * The network log shows that tiles are still being requested, they are simply not rendered.

Any thoughts?

**Comment by thomasmoelhave** [comment] 2015-03-09 20:51
I tested this in Windows and Mac OS X, neither of which exhibit this problem. If this is reproduceable by others, it may be an upstream problem in the Firefox canvas renderer in Linux, triggered by something that happens at higher zoom-levels.

**Comment by ramayer** [comment] 2015-03-09 22:08
Here's a minimal example

**Comment by ahocevar** [comment] 2015-03-10 05:52
What about creating a Mozilla bug report with that minimal example? This clearly looks like like a browser bug.

**Comment by ramayer** [comment] 2015-03-10 08:16
Does it?

The same browser/OS works fine if you remove the "extent: projectionExtent,"  line (which shouldn't have any effect because the map is clearly zoomed to an area within that projection's extent).

**Comment by ahocevar** [comment] 2015-03-10 09:47
That setting does have an effect, because it causes a different coordinate range to be used. If I remember correctly, we've had issues with that in OpenLayers 2 already, with the SVG renderer.

**Comment by thomasmoelhave** [comment] 2015-03-10 14:02
The XYZ example does not use `extent`, so that might be why it does not have this problem.

**Comment by ramayer** [comment] 2015-03-10 16:48
'k.   submitted it to Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1141625

**Comment by jjmontesl** [comment] 2015-08-28 16:51
I'm also seeing this effect. Removing `extent` seems to work.

**Comment by ramayer** [comment] 2015-12-21 19:20
The Firefox guys reproduced the bug, and assigned it to their "Canvas:2D" component guys.

https://bugzilla.mozilla.org/show_bug.cgi?id=1141625

**Comment by emxjay** [comment] 2016-02-26 15:06
@ramayer Thanks for the tip, I was tearing my hair out :)

**Comment by ahocevar** [comment] 2016-02-26 18:08
For me, this issue is fixed in v3.14.0, thanks to #4597. Can anyone confirm and close this?

cc @ramayer,  @emxjay, @jjmontesl, @thomasmoelhave

**Comment by ahocevar** [comment] 2016-02-26 18:08
Fiddle for testing: http://jsfiddle.net/znpkgwat/

**Comment by emxjay** [comment] 2016-02-29 09:05
@ahocevar I confirm. Don't have the rights to close the issue, however.

**Comment by ahocevar** [comment] 2016-02-29 09:05
Thanks for testing @emxjay.

**Closed** 2016-02-29 09:05 UTC
