### ISSUE TITLE
Zooming out to zoom level 0 is broken in bing-maps example

### ISSUE THREAD

**Issue by ahocevar** [openlayers/ol3#3384] opened 2015-03-23 16:43 UTC
Try at http://openlayers.org/en/v3.3.0/examples/bing-maps.html. The map will disappear when zoomed out from zoom level 1 to 0. In development mode, an assertion error is thrown.

I know Bing does not have a zoom level 0, but shouldn't we be able to upsample?

**Comment by elemoine** [comment] 2015-03-23 16:54
Duplicate of https://github.com/openlayers/ol3/issues/2780.

**Comment by ahocevar** [comment] 2015-03-23 16:55
I added #2780 to the next milestone so we get reminded about it at least once a month.

**Closed** 2015-03-23 16:58 UTC
