### ISSUE TITLE
[3.11] doesn't render icon sprites correctly (ol.style.Icon "offset" + "size" options)

### ISSUE THREAD

**Issue by kulmegil** [openlayers/ol3#4406] opened 2015-11-12 15:32 UTC
I was using ol.style.Icon with "offset" and "size" options in v3.10.1 to render individual images from a sprite. But 3.11 doesn't render icon as expected - instead of cropped icon almost whole sprite is rendered for each feature.

OL v3.10.1:
http://jsfiddle.net/fzbrwwpj/1/

OL v3.11:
http://jsfiddle.net/emeacb27/2/

**Comment by bartvde** [comment] 2015-11-12 18:50
caused by https://github.com/openlayers/ol3/pull/4339

**Comment by tschaub** [comment] 2015-11-13 00:02
Fixed with #4413.

**Closed by tschaub** 2015-11-13 00:02 UTC
