### ISSUE TITLE
new ol.source.Vector() - JS error

### ISSUE THREAD

**Issue by kulmegil** [openlayers/ol3#3755] opened 2015-06-02 08:52 UTC
cannot create ol.source.Vector because always getting an error
> TypeError: ol.ext.rbush is not a function

This happens for me when OL is loaded through requireJs
v3.5.0

**Comment by juristr** [comment] 2015-07-15 09:12
same here. Is there any solution for this?

**Comment by ahocevar** [comment] 2015-07-17 16:09
Duplicate of #3155.

**Comment by ahocevar** [comment] 2015-07-17 16:13
@juristr @kulmegil Please try #3910, it should fix the issue.

**Comment by ahocevar** [comment] 2015-07-17 16:16
Duplicate of #3155.

**Closed by ahocevar** 2015-07-17 16:16 UTC
