### ISSUE TITLE
How to set extent property in view after map initialize using openlayer3?

### ISSUE THREAD

**Issue by anudeep86** [openlayers/ol3#5987] opened 2016-10-18 11:32 UTC
My purpose is pan the map upto a certain limit (exactly like google map) after that it should lock. This support is present in Openlayer version 2.0 using Bounds. But in version 3 I have to set extent property while initializing view. I am stuck in this stage. View is not set after initialize the map.

      var map = new ol.Map({
        target: 'map',
        layers: [
          new ol.layer.Tile({
            source: new ol.source.OSM()
          })
        ],
        view: new ol.View({
          center: ol.proj.fromLonLat([73.8, 18.5]),
          zoom: 12
        })
      });
Now I want to set 'extent' property in view

      map.setView(new ol.View({
        center: ol.proj.fromLonLat([73.8, 18.5]),
        extent: map.getView().calculateExtent(map.getSize()),
        zoom : 12
      }));
This code is not working. Is there any other way to do that or am I doing something wrong?
There is no error in console. But map is not display. 
https://jsfiddle.net/nh9fs74k/

**Comment by ahocevar** [comment] 2016-10-18 15:22
You can always set a new view as in your 2nd snippet above. I've also updated your fiddle to show how it is done: https://jsfiddle.net/nh9fs74k/1/.

Note that panning is only restricted if the center of the map falls outside of the specified extent. So what you see in the JSFiddle is expected behaviour.

**Comment by ahocevar** [comment] 2016-10-19 08:47
@anudeep86 Since this question was also asked on both stackoverflow and gis.stackexchange, I'm closing this. Next time, please decide beforehand whether you want to report a bug (here), or have a problem with OpenLayers usage (stackoverflow).

**Closed by ahocevar** 2016-10-19 08:47 UTC

**Comment by anudeep86** [comment] 2016-10-19 10:21
@ahocevar Noted.
