### ISSUE TITLE
Defect? ol.Overlay stopEvents dont stop pointerMove

### ISSUE THREAD

**Issue by DavidHequet** [openlayers/ol3#5068] opened 2016-03-17 17:06 UTC
Hi,

As i read the API doc, ol.Overlay with stopEvents option to true must stop event, but it seems to stop only click event. 

When you use a listener top map pointermove, it dosn't stop on overlay:

Here is a simple example, using the standard ( http://openlayers.org/en/v3.14.2/examples/overlay.html ) sample and adding an ol.control.MousePosition(). 

If you move the mouse over the popup, Mouseposition is updated, i think it shouldn't
Jsfiddle : http://jsfiddle.net/dxmL8t8t/
Thank you,
David

**Comment by ahocevar** [comment] 2016-03-18 08:31
Duplicate of #4953, closing.

**Closed by ahocevar** 2016-03-18 08:31 UTC
