### ISSUE TITLE
Map is blurry when browser is zoomed

### ISSUE THREAD

**Issue by alanthai** [openlayers/ol3#3320] opened 2015-03-05 15:45 UTC
If the internet browser isn't at 100% zoom level, the map will look blurry. You can try this on Chrome or Firefox by pressing [Ctrl]+[-] or [Ctrl]+[+]. Reverting to a 100% zoom level won't sharpen the image until you do a page refresh.

Here's a comparison:
![Blurry map comparison](http://i.stack.imgur.com/D8pVg.png)

Clear map:
![Clear map detail](http://i.stack.imgur.com/BmePi.png)

Blurry map (should be similar dimensions as the clear map):
![Fuzzy map detail](http://i.stack.imgur.com/qOn3e.png)

The issue has to do with the intial instantiation of map.frameState_.pixelRatio not being updated when zoom level changes.

Also posted on StackOverflow:
http://stackoverflow.com/questions/28880093/openlayers-3-map-is-blurry

**Comment by fredj** [comment] 2015-03-05 16:18
duplicate of #2904

**Closed by fredj** 2015-03-05 16:18 UTC
