### ISSUE TITLE
reprojection-wgs84 example partially rendering wrong tiles on zoom

### ISSUE THREAD

**Issue by probins** [openlayers/ol3#4589] opened 2015-12-23 11:24 UTC
http://openlayers.org/en/v3.12.1/examples/reprojection-wgs84.html
Dbl-click in Europe to zoom in, and the tiles for the top/N part of Europe remain those for the previous resolution. Repeated zoom repeats the mismatch.

Tested on Chrome 47, laptop and Android.

**Comment by ahocevar** [comment] 2015-12-23 11:40
Duplicate of #4124.

**Closed by ahocevar** 2015-12-23 11:40 UTC

**Comment by probins** [comment] 2015-12-23 12:37
Not sure I entirely understand 4124. This is not really 'magnification'; the different zoom levels/resolutions on raster tiles like OSM provide different levels of detail: more map detail is displayed the more you zoom in. If I understand 4124 correctly, the reprojection process for the top half of this screenshot is coming up with a resolution in the to-projection that does not correspond to that of the from-projection, so is reprojecting the wrong tile. Is that correct?

If so, that's quite a major limitation. As far as the user's concerned, the display is not really usable.
![screenshot 2015-12-23 at 12 04 51](https://cloud.githubusercontent.com/assets/283514/11976181/84b2afac-a96d-11e5-8c14-a5b13d651c39.png)

**Comment by petrsloup** [comment] 2015-12-26 11:02
See http://openlayers.org/en/master/doc/tutorials/raster-reprojection.html#resolution-calculation (the last paragraph on the page).
