### ISSUE TITLE
Unable to use SVG image as layer

### ISSUE THREAD

**Issue by Mattie112** [openlayers/ol3#4633] opened 2016-01-07 13:22 UTC
Hi All,

I'm sorry to post it here but I did not get any good information on stackoverflow.

My question is simple: Can I use a SVG image as a layer with OpenLayers-3? I did not find anything on the website but because it is such a commonly used format I want to be sure.

For reference my question on stackoverflow: https://stackoverflow.com/questions/34416412/how-can-i-use-a-svg-image-as-layer-on-openlayers-3

**Comment by bmrainc** [comment] 2016-12-13 08:48
The same question!

**Comment by ahocevar** [comment] 2016-12-13 09:48
The question was properly [answered on Stackoverflow](https://stackoverflow.com/questions/34416412/how-can-i-use-a-svg-image-as-layer-on-openlayers-3), so closing.

**Closed by ahocevar** 2016-12-13 09:48 UTC

**Comment by Status420** [comment] 2017-03-23 15:30
I disagree with this, as if you use this example which uses imageStatic, the image becomes blurred on zoom and doesn't  remain smooth as you'd expect a SVG to do.

**Comment by pumppi** [comment] 2017-03-26 08:39
I have same issue. SVG goes blurred with newst version, but the old version works fine.

**Comment by ahocevar** [comment] 2017-03-26 09:46
The reason why you did not see any blur in previous versions is because there wheel zooming was always snapped to integer zoom levels, which it is no longer.

And the reason why the SVG gets blurred at fractional zoom levels is because it is rendered to a canvas and composed to a final map image with the other layers.

**Comment by Status420** [comment] 2017-03-27 08:38
So how do we work around this? Stay on the old version?  We need smooth SVG layers on our maps.

**Comment by Kardzhilov** [comment] 2018-04-18 18:53
Still no solution?

**Comment by svpasumarthy** [comment] 2019-02-01 19:12
any fix for this issue yet? or anyone with alternative approach?

**Comment by Koronag** [comment] 2019-11-27 02:44
Hi. I've looked at the documentation for the render property in the Layer class:
https://openlayers.org/en/master/apidoc/module-ol_layer_Layer-Layer.html

but i do not understand what input this property is expecting. What is the "frame state" and how do i return this?

**Comment by ahocevar** [comment] 2019-12-01 11:35
@Koronag I have just created pull request #10363 with a new `svg-layer.html` example that should answer your question. Until that pull request is merged, you can preview the example: https://473-4974939-gh.circle-artifacts.com/0/examples/svg-layer.html

**Comment by ShantanuParode** [comment] 2022-06-09 06:10
@ahocevar Hi
I was facing issues when adding a Static Image Source to the SVG layer that you created in this example [SVG Layer](https://openlayers.org/en/latest/examples/svg-layer.html). I tried providing the Layer some projection like in this example [Image Reprojection](https://openlayers.org/en/latest/examples/reprojection-image.html). But the layer is not picking up the projection and I am not able to change the position, size and rotation of the image layer on the map. The SVG is always getting rendered at lon-lat [0, 0]. But the same projection is working when provided to a [static image layer.](https://openlayers.org/en/latest/examples/static-image.html).

Sorry, I cannot provide any reproduction of this at this moment. But if possible, can you please create an example where SVG image ([let's say this](https://upload.wikimedia.org/wikipedia/commons/f/fd/Ghostscript_Tiger.svg)) is rendered on map at some point (lon lat [-72, 42]) and size should be relative?

Looking forward to your reply. 

One more thing, it was possible to render SGV directly as Static Image in OL-3, but as you explained earlier, it is not possible now. I cannot go back to the previous version, but can you please make it easier to render SVG like the OL-3? Please consider this as a feature request.

**Comment by ahocevar** [comment] 2022-06-09 10:14
Nothing keeps you from adding an SVG as static image layer. But it will be blurry because it is rendered to a canvas at the SVG's native resolution. Hence the better way of using a render function. The `svg-layer` example is made so it can align with other data, see e.g. https://codesandbox.io/s/svg-layer-forked-8rc6cu. If it doesn't align for you with a static image, you need to make sure the `cssTransform` of the SVG layer matches the `extent` of the ImageStatic layer.

Your other request (rendering an SVG at a location with relative size) is just an ol/style/Icon exercise with a `scale` calculated from the current view resolution.

**Comment by ShantanuParode** [comment] 2022-06-13 10:07
Thanks for the reply. @ahocevar 
I understood that I have to write a render function to display the svg on the map.
Please refer this example. [https://codesandbox.io/s/svg-layer-forked-cvcpvd](https://codesandbox.io/s/svg-layer-forked-cvcpvd)
Here I want to adjust the width of the svg building to 10 meters. And the building should render at lon lat [20, 20]. Also the [20, 20] should be the center point of the building on map.  But I am having difficulty writing the render function. Can you please help writing the render function for this example? Please edit the example as required.

**Comment by Raynoxis** [comment] 2024-04-21 18:34
Hello, i use a svg like this as a layer, but i cannot see other layer with it. it seems the render function, always hide others layers... 
Thank you so much

**Comment by ahocevar** [comment] 2024-04-21 21:32
With the new `ImageSource` loader API, it is no longer necessary to use a custom render function. See e.g. https://openlayers.org/en/latest/examples/wms-image-svg.html for SVGs from a WMS.
