### ISSUE TITLE
Tiles disappearing on pan when zoom level change is big

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3#4566] opened 2015-12-15 20:10 UTC
Found this out in a screenshare with @ahocevar just now, to reproduce go to:

http://openlayers.org/en/v3.12.0/examples/xyz-esri.html

Zoom in with a very small bbox, and then pan the map. The tiles will blur completely sometimes. In 3.11.2 you will see a small section blurred only, where no tiles are present as yet.

**Comment by fredj** [comment] 2015-12-15 21:21
Caused by #4536 ?

**Comment by bartvde** [comment] 2015-12-16 07:51
No that doesn't seem to be the cause @fredj I'll investigate what caused it.

**Comment by bartvde** [comment] 2015-12-16 07:57
seems to be caused by https://github.com/openlayers/ol3/commit/0259977fa95da120b38d56eac0b020190e4cfb22

**Comment by bartvde** [comment] 2015-12-16 08:00
maybe because we got rid of ```goog.array.defaultCompare``` ?

**Comment by marcjansen** [comment] 2015-12-16 08:34
Can the regression be fixed by always passing a `compareFn` in cases where we currently don't pass one)?

```javascript
function(a, b) {
  return a > b ? 1 : a < b ? -1 : 0;
}
```
https://github.com/google/closure-library/blob/master/closure/goog/array/array.js#L1298

**Comment by bartvde** [comment] 2015-12-16 08:34
yes that's actually the PR I'm preparing now

**Comment by marcjansen** [comment] 2015-12-16 08:42
:+1:

**Closed** 2015-12-16 10:35 UTC
Labels: regression
