### ISSUE TITLE
What is the recommended way to hack into OL3 source code?

### ISSUE THREAD

**Issue by htulipe** [openlayers/ol3#3877] opened 2015-07-06 13:50 UTC
With the "compiled" version of OL3, any method that is not flagged as public cannot be accessed by developpers. This represents a problem in some case. 

For instance I would like to override `ol.format.KML.writePlacemark_` to handle a business specific case but, as far as I can tell, this can not be done with OL3 "compiled".

While I can understand the benefit of private/public methods, there often will be a need to hack into the code to adapt library to business needs. Hence my question, what is the recommended way to hack into OL3 source code? 

The only way I see right now is to maintain my own version of the library and compile it myself along with my additions. While this a doable solution, this is a really unpractical one.

**Comment by pconnell99** [comment] 2015-07-23 14:53
This has been my solution - I needed x/y scaling for vector icons and it didn't seem like it was going to be implemented so I downloaded, rewrote and compiled my own library to do it - it's cumbersome but works - you then have to merge your changes every so often and hope nothing too much has changed  in the meantime.

It is doable, but it is also a pain.  I'm currently on a 3.6.XX build from trunk with my mods, so no idea if I'm harbouring bugs.

**Comment by elemoine** [comment] 2015-08-06 06:12
> While I can understand the benefit of private/public methods, there often will be a need to hack into the code to adapt library to business needs. Hence my question, what is the recommended way to hack into OL3 source code?

As @pconnell99 mentioned you can have your own fork/branch with your additions and create specific builds.

We can also add hooks to ol3 when possible and relevant to make ol3 more extensible to people. For example. `writePlacemark_` could call a user-defined function for specific treatments.

I am going to close the issue, but feel free to continue the discussion here.

**Closed** 2015-08-06 06:12 UTC

**Comment by htulipe** [comment] 2015-08-06 11:14
I finally went for a private fork with rebasing to keep my code up to date.

I think there is a real need to make the library more extensible, not being able to do so is an important drawback for a Javascript based library.

I like the idea of hooks but it would need to be a general mechanism: today I need to change `_writePlacemark` but tomorrow another person will want to change another private method of some other format. Wouldn't it be simpler to refactor format to allow override of the `ol.format.*_PARSERS_` and `ol.format.*_SERIALIZERS_` variables? Today those variables are private scoped, I think it could make sense to expose them as public (or at least protected).

**Comment by elemoine** [comment] 2015-08-07 05:08
FWIW the issue is not related to "public versus protected vs private". It's related to variable renaming by the compiler.

**Comment by htulipe** [comment] 2015-08-07 07:56
So it could be possible to only not rename those variables? It would also be necessary to expose `ol.xml` methods.

**Comment by pconnell99** [comment] 2015-08-07 08:43
The compiler does a lot of optimisations, I'm not 100% up on how it works but I suppose you COULD tell it to not shorten certain  functions, but overall, the compressed, compiled version is not going to be extensible over and above the hooks that the development team write.

ol-debug.js is easier to work with, but bigger obviously.  You can trace functions through that and see how they work, but the overhead is there on (I assume) size and speed.

**Comment by probins** [comment] 2015-08-07 08:52
with a custom build you can export whatever values you like, though if they're not part of the public api there's no commitment that they'll remain the same in the future. I would however question this approach. Custom builds are mainly for excluding bits of code you don't need; the compiler is very good at this. The formats are there for converting standard text strings into OL features. If you don't like the way that works, then either use the format to read the features and then do whatever to those features before adding them to the map, or write your own code to convert the incoming data. I use several JSON sources that are not standatd GeoJSON; I did consider extending the OL class but decided it was easier to just write my own code to convert the incoming data into feature and not use OL format.
