### ISSUE TITLE
UpdateParams makes the TileWMS layer flicker when called for the first time

### ISSUE THREAD

**Issue by rrutkows** [openlayers/ol3#5617] opened 2016-07-19 15:40 UTC
OL 3.15
1. Create a TileWMS source without providing an URL in the options.
2. Pass the URLs with the `setUrls` method.
3. Call updateParams after the layer is displayed.
When called for the first time, `updateParams` makes the layer flicker. Probably because `coordKeyPrefix_` is set to an empty string initially. Shouldn't `setUrls` call `resetCoordKeyPrefix_`?

**Comment by ahocevar** [comment] 2016-07-19 17:30
This should have been fixed in the meantime. Can you try with v3.17.1 or master?

**Comment by rrutkows** [comment] 2016-07-20 07:36
Tested with 3.17.1 and the issue is there too.

In both 3.15 and 3.17, it's OK, if you pass the urls in the constructor instead of `setUrls`.

**Comment by ahocevar** [comment] 2016-07-20 08:30
You mean you get the flicker with `updateParams()` every time *after* you have used `setUrls()`? If the problem is what you suspect above, would you be able to create a pull request with a fix?

**Comment by rrutkows** [comment] 2016-07-20 09:34
No, only the first time. `updateParams` resets the `coordKeyPrefix_` to reflect the current urls, so `coordKeyPrefix_` does not change anymore on subsequent `updateParams` calls.

I'll prepare that pull request.

**Closed** 2016-07-21 09:38 UTC
Labels: pull request accepted
